ChEn-3170: Computational Methods in Chemical Engineering Fall 2021 UMass Lowell; Prof. V. F. de Almeida **07Sep21**

# 04. Array Operations
$  
  \newcommand{\Amtrx}{\boldsymbol{\mathsf{A}}}
  \newcommand{\Bmtrx}{\boldsymbol{\mathsf{B}}}
  \newcommand{\Cmtrx}{\boldsymbol{\mathsf{C}}}
  \newcommand{\Dmtrx}{\boldsymbol{\mathsf{D}}}
  \newcommand{\Mmtrx}{\boldsymbol{\mathsf{M}}}
  \newcommand{\Imtrx}{\boldsymbol{\mathsf{I}}}
  \newcommand{\Pmtrx}{\boldsymbol{\mathsf{P}}}
  \newcommand{\Qmtrx}{\boldsymbol{\mathsf{Q}}}
  \newcommand{\Lmtrx}{\boldsymbol{\mathsf{L}}}
  \newcommand{\Umtrx}{\boldsymbol{\mathsf{U}}}
  \newcommand{\xvec}{\boldsymbol{\mathsf{x}}}
  \newcommand{\avec}{\boldsymbol{\mathsf{a}}}
  \newcommand{\bvec}{\boldsymbol{\mathsf{b}}}
  \newcommand{\vvec}{\boldsymbol{\mathsf{v}}}
  \newcommand{\cvec}{\boldsymbol{\mathsf{c}}}
  \newcommand{\rvec}{\boldsymbol{\mathsf{r}}}
  \newcommand{\norm}[1]{\bigl\lVert{#1}\bigr\rVert}
  \DeclareMathOperator{\rank}{rank}
$

---
## Table of Contents<a id="toc">
* [Objectives](#obj)
* [Formatting Output](#format)
* [Vectors](#vectors)
   + [Element-by-element addition/subtraction](#vecaddsub)
   + [Element-by-element product/division](#vecproddiv)
   + [Self product](#vecselfprod)
   + [Inner product (dot product)](#vecinnerprod)
   + [Scaling (element-by-element multiplication/division by scalar)](#vecscale)
   + [Element-by-element mathematical operations](#vecops)
   + [Element-by-element search](#vecsearch)
   + [Zip vectors](#veczip)
* [Matrices](#matrices)
   + [Element-by-element addition/subtraction](#mataddsub)
   + [Element-by-element product/division](#matproddiv)
   + [Scaling (element-by-element multiplication/division by scalar)](#matscale)
   + [Element-by-element mathematical operations](#matops)
   + [Transposition](#mattransp)
     - `Numpy` `set_printoptions()` method
   + [Element-by-element search](#matsearch)
---

## [Objectives](#toc)<a id="obj"></a>

 + Cover basic array operations in 1-D (vectors) and 2-D (matrices) needed throughout the course.

In [1]:
'''Python packages are accessed with an import directive as such:'''

import numpy as np  # import the package and create the alias: np

## [Formatting Output](#toc)<a id="format"></a>

* Scientific notation

In [2]:
import math

pi = math.pi

print('pi = %15.5e'%pi) # formatting numeric output: scientific notation

pi =     3.14159e+00


In [3]:
print('pi = %10.5f'%pi) # formatting numeric output: float

pi =    3.14159


In [4]:
print('pi = %10.5e and e = %8.3f'%(pi, math.e)) # formatting numeric output: sci. notation and float

pi = 3.14159e+00 and e =    2.718


* `Numpy` arrays

In [8]:
'''Use set print options in Numpy'''

np.set_printoptions(precision=4, threshold=800, edgeitems=6, linewidth=105)

mtrx = np.random.random((10,100))

print(mtrx)

[[0.9215 0.9218 0.7109 0.4418 0.9413 0.8651 ... 0.5199 0.5011 0.5848 0.9507 0.1476 0.979 ]
 [0.0376 0.0666 0.8694 0.1449 0.3423 0.8301 ... 0.2515 0.997  0.3298 0.6762 0.9248 0.9762]
 [0.0071 0.5879 0.5378 0.6471 0.6322 0.163  ... 0.4565 0.9912 0.3902 0.1685 0.099  0.3509]
 [0.6045 0.1973 0.0101 0.5103 0.3824 0.8464 ... 0.2924 0.8902 0.3819 0.5871 0.5313 0.5782]
 [0.8055 0.7514 0.7962 0.8436 0.9439 0.7194 ... 0.1047 0.1044 0.1089 0.0221 0.7562 0.6254]
 [0.2605 0.2035 0.457  0.3711 0.2247 0.9766 ... 0.4028 0.7215 0.9177 0.8254 0.221  0.1166]
 [0.1695 0.0125 0.386  0.7931 0.9483 0.8453 ... 0.2989 0.7226 0.6534 0.4342 0.7322 0.3836]
 [0.0733 0.0361 0.6943 0.5707 0.5822 0.4915 ... 0.4477 0.9527 0.2062 0.83   0.735  0.9048]
 [0.6323 0.3215 0.3455 0.5195 0.97   0.114  ... 0.4645 0.4024 0.4912 0.8287 0.368  0.4807]
 [0.2051 0.2612 0.0541 0.8466 0.1075 0.6887 ... 0.9908 0.5424 0.1062 0.1758 0.8317 0.1861]]


In [ ]:
#help(np.set_printoptions)

## [Vectors](#toc)<a id="vectors"></a>

**In all of engineering calculations use double-precision floating point numeric**

In [9]:
'''Set double precision at creation time'''

x_vec = np.empty(10, dtype=np.float64)

print(type(x_vec))
print(x_vec.dtype)

<class 'numpy.ndarray'>
float64


In [10]:
'''Set double precision after creation'''

x_vec = x_vec.astype(float)
print(type(x_vec))
print(x_vec.dtype)

<class 'numpy.ndarray'>
float64


#### [Element-by-element addition/subtraction](#toc)<a id="vecaddsub"></a>

In [11]:
'''Element-by-element addition or subtraction'''

vec1 = np.array(np.random.random(5))
print('vec1     =',vec1)

vec2 = np.array(np.random.random(5))
print('vec2     =',vec2)

result = vec1 + vec2         # element-by-element sum
print('addition   =',result)

result = vec1 - vec2         # element-by-element subtraction
print('difference =',result)

vec1     = [0.7803 0.3296 0.6576 0.3031 0.425 ]
vec2     = [0.7695 0.4493 0.3633 0.5821 0.6555]
addition   = [1.5498 0.7789 1.021  0.8853 1.0805]
difference = [ 0.0108 -0.1197  0.2943 -0.279  -0.2305]


#### [Element-by-element product/division](#toc)<a id="vecproddiv"></a>

In [12]:
'''Element-by-element product or division'''

vec1 = np.array(np.random.random(5))
print('vec1    =',vec1)

vec2 = np.array(np.random.random(5))
print('vec2    =',vec2)

result = vec1 * vec2        # element-by-element product
print('product  =',result)

result = vec1 / vec2        # element-by-element division
print('division =',result)

vec1    = [0.7546 0.5069 0.7965 0.0492 0.8305]
vec2    = [0.1704 0.1345 0.2311 0.2581 0.9795]
product  = [0.1286 0.0682 0.1841 0.0127 0.8135]
division = [4.4296 3.7694 3.4471 0.1905 0.8478]


#### [Self product](#toc)<a id="vecselfprod"></a>

In [13]:
'''Product of all elements of a vector'''

vec1_prod = np.prod(vec1)

print('vec1         =', vec1)
print('vec1 product =', vec1_prod)

vec1         = [0.7546 0.5069 0.7965 0.0492 0.8305]
vec1 product = 0.012438104953125705


#### [Inner product (dot product)](#toc)<a id="vecinnerprod"></a>

The result of the inner product of two vectors: $\vvec_1 \cdot \vvec_2$ is a scalar.

In [14]:
'''Vector inner product or dot product'''

vec1 = np.array(np.random.random(5))
print('vec1           =',vec1)

vec2 = np.array(np.random.random(5))
print('vec2           =',vec2)

result = np.dot(vec1, vec2)     # inner or dot product
print('dot product =',result)

vec1           = [0.8281 0.1662 0.8479 0.5177 0.5513]
vec2           = [0.52   0.5915 0.0327 0.1878 0.5023]
dot product = 0.9308175368384498


In [15]:
'''More on vector inner product or dot product'''
'''Another way to compute the inner product'''

ele_by_ele_product = vec1 * vec2

inner_product = ele_by_ele_product.sum()

print('vec1 . vec2 = ', inner_product)

vec1 . vec2 =  0.9308175368384499


#### [Scaling (element-by-element multiplication/division by a scalar)](#toc)<a id="vecscale"></a>

In [16]:
'''Scaling of a vector'''

vec = np.array(np.random.random(5))
print('vec    =',vec)

factor = 0.345
scaled = factor * vec     # scaling of vec element-by-element product
print('scaled =', scaled) # assigned to new variable `scaled`

vec *= factor          # in-place scaling
print('vec    =',vec)

vec    = [0.8841 0.6296 0.928  0.475  0.0811]
scaled = [0.305  0.2172 0.3202 0.1639 0.028 ]
vec    = [0.305  0.2172 0.3202 0.1639 0.028 ]


#### [Element-by-element mathematical operations](#toc)<a id="vecops"></a>

In [17]:
'''Mathematical Operations on a Vector'''

vec = np.array(np.random.random(5))
print('vec      =',vec)

log_vec = np.log(vec)         # natural log element-by-element
print('log(vec) =',log_vec)

exp_vec = np.exp(log_vec)     # exponential
print('exp(vec) =',exp_vec)

sin_vec = np.sin(vec)         # sine
print('sin(vec) =',sin_vec)

vec_cubed = vec**3            # powers
print('vec^3    =',vec_cubed)

vec_mean = vec.mean()         # arithmetic mean
print('mean(vec) =',vec_mean)

vec_std = vec.std()           # standard deviation
print('std(vec) =',vec_std)

vec      = [0.9718 0.5388 0.0355 0.2574 0.4081]
log(vec) = [-0.0286 -0.6185 -3.3369 -1.3573 -0.8961]
exp(vec) = [0.9718 0.5388 0.0355 0.2574 0.4081]
sin(vec) = [0.8259 0.5131 0.0355 0.2545 0.3969]
vec^3    = [9.1783e-01 1.5639e-01 4.4911e-05 1.7047e-02 6.7990e-02]
mean(vec) = 0.44233045763697654
std(vec) = 0.3132146291074491


#### [Element-by-element search](#toc)<a id="vecsearch"></a>

In [18]:
'''Searching a vector for entries matching a test'''

# what are the indices of the values in "vec" that satisfy: vec[] >= 0.3
(idx_ids, ) = np.where(vec >= 0.3) 

print('vec =', vec)
print('indices = ', idx_ids)

vec = [0.9718 0.5388 0.0355 0.2574 0.4081]
indices =  [0 1 4]


In [19]:
'''Searching a vector for entries matching a test'''

# what are the indices of the values in "vec" that satisfy: vec[] == 0.3
(idx_ids, ) = np.where(vec == 0.3) 

print('vec =', vec)
print('indices = ', idx_ids)

vec = [0.9718 0.5388 0.0355 0.2574 0.4081]
indices =  []


#### [Zip vectors](#toc)<a id="veczip"></a>

In [20]:
'''Zip creates tuples on the fly'''

print(list(zip(vec1, vec2)))

[(0.8280746383285155, 0.5199899618527384), (0.166219088045082, 0.5914651714365978), (0.8479341351663676, 0.03270298172977504), (0.5177128132871368, 0.18778090168107842), (0.5513442954808506, 0.5023497743334875)]


In [21]:
zip(vec1,vec2)

## [Matrices](#toc)<a id="matrices"></a>

**In all of engineering calculations use double-precision floating point numeric**

In [ ]:
'''Set double precision at creation time'''

mtrx = np.empty((5,5), dtype=np.float64)

print(type(mtrx))
print(mtrx.dtype)

In [ ]:
'''Set double precision after creation'''

mtrx = mtrx.astype(float)
print(type(mtrx))
print(mtrx.dtype)

#### [Element-by-element addition/subtraction](#toc)<a id="mataddsub"></a>

In [ ]:
'''Element-by-element addition or subtraction'''

mat1 = np.random.random((3,3))
print('mat1       =\n', mat1)

mat2 = np.random.random((3,3))
print('mat2       =\n', mat2)

result = mat1 + mat2              # element-by-element sum
print('addition   =\n', result)

result = mat1 - mat2              # element-by-element subtraction
print('difference =\n', result)

#### [Element-by-element product/division](#toc)<a id="matproddiv"></a>

In [ ]:
'''Element-by-element product or division'''

mat1 = np.random.random((3,3))
print('mat1     =\n', mat1)

mat2 = np.random.random((3,3))
print('mat2     =\n', mat2)

result = mat1 * mat2          # element-by-element product
print('product  =\n', result)

result = mat1 / mat2          # element-by-element division (cross your fingers)
print('division =\n', result)

In [ ]:
'''Produce Noise on a Matrix Image (brick data)'''

from matplotlib import pyplot as plt     # import the pyplot function of the matplotlib package
#%matplotlib inline
plt.rcParams['figure.figsize'] = [20, 4] # extend the figure size on screen output

# Read image from the images/ directory in the chen-3170 repo
block = plt.imread('images/glacier.png', format='png')

plt.figure(1)
plt.imshow(block)
plt.title('Matrix Reloaded', fontsize=14)
plt.show()
print('block shape =', block.shape)  # inspect the array shape

In [ ]:
'''Use Matrix Element-by-Element Multiplication'''

mtrx_shape = block.shape[0:2]                 # use the shape to automate noise_mtrx generation

noise_mtrx = np.random.random(mtrx_shape)   # generate random matrix

block_noise = block[:,:,2] * noise_mtrx   # apply noise to the blue channel

plt.figure(2)
plt.imshow(block_noise)
plt.title('Noisy Block',fontsize=14)
plt.show()

In [ ]:
'''Matrix Scaling (matrix product or division by a scalar)'''

mat1 = np.random.random((3,3))
print('mat1      =\n',mat1)

factor = 3.21
result = factor * mat1        # scaling of mat1 element-by-element; product with factor
print('scaled   =\n',result)

#### [Scaling (element-by-element multiplication/division by a scalar)](#toc)<a id="matscale"></a>

In [ ]:
'''Matrix Scaling of an Image'''

color_channel = np.copy(block[:,:,0])   # copy the red channel

color_channel /= color_channel.max()    # scale to gray, 0-255 values
color_channel *= 255
gray_channel  = color_channel.astype(int) # truncate all float data type to int

plt.figure(3)
plt.imshow(gray_channel, cmap='gray')

plt.title('Matrix Gray Scaling',fontsize=14)
plt.show()

#### [Element-by-element mathematical operations](#toc)<a id="matops"></a>

In [ ]:
'''Other Mathematical Operations on a Matrix'''

mtrx = np.copy(block[:,:,0])    # copy the red channel

plt.figure(4)
plt.imshow(mtrx)              # show channel as a flat image with default colormap
plt.title('Original', fontsize=14)
plt.show()

mtrx_mean = mtrx.mean()         # arithmetic mean
print('mean(mtrx) =', mtrx_mean)

mtrx_std = mtrx.std()           # standard deviation
print('std(mtrx) =', mtrx_std)

In [ ]:
'''Other Mathematical Operations on a Matrix'''

log_mtrx = np.log(mtrx + .001)  # natural log element-by-element

plt.figure(5)
plt.imshow(log_mtrx)
plt.title('Log Transform', fontsize=14)
plt.show()

mtrx_mean = log_mtrx.mean()         # arithmetic mean
print('mean(mtrx) =', mtrx_mean)

mtrx_std = log_mtrx.std()           # standard deviation
print('std(mtrx) =', mtrx_std)

In [ ]:
'''Other Mathematical Operations on a Matrix'''

exp_mtrx = np.exp(log_mtrx)     # exponential

plt.figure(6)
plt.imshow(exp_mtrx)
plt.title('Exp of Log Transform', fontsize=14)
plt.show()

mtrx_mean = exp_mtrx.mean()         # arithmetic mean
print('mean(mtrx) =', mtrx_mean)

mtrx_std = exp_mtrx.std()           # standard deviation
print('std(mtrx) =', mtrx_std)

In [ ]:
'''Other Mathematical Operations on a Matrix'''

sin_mtrx = np.sin(mtrx + np.pi/2)  # sine

plt.figure(7)
plt.imshow(sin_mtrx)
plt.title('Sine Transform', fontsize=14)
plt.show()

mtrx_mean = sin_mtrx.mean()         # arithmetic mean
print('mean(mtrx) =', mtrx_mean)

mtrx_std = sin_mtrx.std()           # standard deviation
print('std(mtrx) =', mtrx_std)

In [ ]:
'''Other Mathematical Operations on a Matrix'''

mtrx_cubed = mtrx**3  # powers

plt.figure(8)
plt.imshow(mtrx_cubed)
plt.title('Cube Transform', fontsize=14)
plt.show()

mtrx_mean = mtrx_cubed.mean()         # arithmetic mean
print('mean(mtrx) =', mtrx_mean)

mtrx_std = mtrx_cubed.std()           # standard deviation
print('std(mtrx) =', mtrx_std)

#### [Transposition](#toc)<a id="mattransp"></a>

In [ ]:
'''Matrix Transposition'''
'''clockwise rotation followed by horizontal right to left flip'''

mtrx = np.random.random((5,7))

np.set_printoptions(precision=3,threshold=20,edgeitems=12,linewidth=100) # one way to control printing of numpy arrays

print('mtrx =\n',mtrx)

mtrx_T = mtrx.transpose()       # transpose of a mtrx: M[i,j] -> M[j,i]

print('mtrx^T =\n',mtrx_T)

In [ ]:
'''Matrix Transposition'''
'''Example of adding a transformed matrix to another transform transposed'''

'''note: to add a matrix to its transpose, a matrix must be square'''

n_rows = block.shape[0]
n_columns = n_rows

mtrx = np.copy(block[:n_rows,:n_columns,0])   # select a square block; red channel

sin_mtrx = np.sin(mtrx + np.pi/2)  # sine

sin_mtrx /= sin_mtrx.max()
plt.figure(9)
plt.imshow(sin_mtrx)
plt.title('Sine Transform', fontsize=14)
plt.show()

mtrx_cubed = mtrx**3                # powers

plt.figure(10)
plt.imshow(mtrx_cubed)
plt.title('Cube Transform', fontsize=14)
plt.show()

plt.figure(11)
plt.imshow(sin_mtrx + mtrx_cubed.transpose())    # sine + cubed transposed
plt.title('Sine + Cube Transpose Transform', fontsize=14)
plt.show()

#### [Element-by-element search](#toc)<a id="matsearch"></a>

In [ ]:
'''Searching a matrix for entries matching a test'''

# what are the indices of the values in "mtrx" that satisfy: mtrx >= 0.3
(idx_ids, jdx_ids) = np.where(mtrx >= 0.3) 

np.set_printoptions(precision=3, threshold=20, edgeitems=5, linewidth=100) 

print('matrix =\n', mtrx)
print('ith indices = ',idx_ids)
print('jth indices = ',jdx_ids)

In [ ]:
'''Verify the searched elements'''

mtrx[idx_ids, jdx_ids].min()