ChEn-3170: Computational Methods in Chemical Engineering Spring 2023 UMass Lowell; Prof. V. F. de Almeida **03Feb23**

# 04. Array Operations
$  
  \newcommand{\Amtrx}{\boldsymbol{\mathsf{A}}}
  \newcommand{\Bmtrx}{\boldsymbol{\mathsf{B}}}
  \newcommand{\Cmtrx}{\boldsymbol{\mathsf{C}}}
  \newcommand{\Dmtrx}{\boldsymbol{\mathsf{D}}}
  \newcommand{\Mmtrx}{\boldsymbol{\mathsf{M}}}
  \newcommand{\Imtrx}{\boldsymbol{\mathsf{I}}}
  \newcommand{\Pmtrx}{\boldsymbol{\mathsf{P}}}
  \newcommand{\Qmtrx}{\boldsymbol{\mathsf{Q}}}
  \newcommand{\Lmtrx}{\boldsymbol{\mathsf{L}}}
  \newcommand{\Umtrx}{\boldsymbol{\mathsf{U}}}
  \newcommand{\xvec}{\boldsymbol{\mathsf{x}}}
  \newcommand{\avec}{\boldsymbol{\mathsf{a}}}
  \newcommand{\bvec}{\boldsymbol{\mathsf{b}}}
  \newcommand{\vvec}{\boldsymbol{\mathsf{v}}}
  \newcommand{\cvec}{\boldsymbol{\mathsf{c}}}
  \newcommand{\rvec}{\boldsymbol{\mathsf{r}}}
  \newcommand{\norm}[1]{\bigl\lVert{#1}\bigr\rVert}
  \DeclareMathOperator{\rank}{rank}
$

---
## Table of Contents<a id="toc">
* [Objectives](#obj)
* [Formatting Output](#format)
   + `Numpy` `set_printoptions()` method
* [Vectors](#vectors)
   + [Element-by-element addition/subtraction](#vecaddsub)
   + [Element-by-element product/division](#vecproddiv)
   + [Self product](#vecselfprod)
   + [Inner product (dot product)](#vecinnerprod)
   + [Scaling (element-by-element multiplication/division by scalar)](#vecscale)
   + [Element-by-element mathematical operations](#vecops)
   + [Element-by-element search](#vecsearch)
   + [Zip vectors](#veczip)
* [Matrices](#matrices)
   + [Element-by-element addition/subtraction](#mataddsub)
   + [Element-by-element product/division](#matproddiv)
   + [Scaling (element-by-element multiplication/division by scalar)](#matscale)
   + [Element-by-element mathematical operations](#matops)
   + [Transposition](#mattransp)
     - `Numpy` `set_printoptions()` method
   + [Element-by-element search](#matsearch)
---

## [Objectives](#toc)<a id="obj"></a>

 + Cover basic array operations in 1-D (vectors) and 2-D (matrices) needed throughout the course.

In [1]:
'''Python packages are accessed with an import directive as such:'''

import numpy as np  # import the package and create the alias: np

## [Formatting Output](#toc)<a id="format"></a>

* Scientific notation

In [2]:
import math

pi = math.pi

print('pi = %15.5e'%pi) # formatting numeric output: scientific notation

pi =     3.14159e+00


In [3]:
print('pi = %10.5f'%pi) # formatting numeric output: float

pi =    3.14159


In [4]:
print('pi = %10.5e and e = %8.3f'%(pi, math.e)) # formatting numeric output: sci. notation and float

pi = 3.14159e+00 and e =    2.718


* `Numpy` arrays

In [5]:
'''Use set print options in Numpy'''

np.set_printoptions(precision=4, threshold=800, edgeitems=6, linewidth=105)

mtrx = np.random.random((10,100))

print(mtrx)

[[0.582  0.6876 0.071  0.3475 0.6306 0.1861 ... 0.1527 0.6775 0.1551 0.7387 0.3409 0.5303]
 [0.3873 0.6623 0.7239 0.539  0.2724 0.7637 ... 0.317  0.7799 0.1639 0.3027 0.0711 0.282 ]
 [0.9471 0.5468 0.6734 0.7841 0.8853 0.227  ... 0.7535 0.4375 0.849  0.3984 0.9268 0.0093]
 [0.4055 0.6629 0.2106 0.6711 0.8134 0.8697 ... 0.6531 0.4995 0.2684 0.0383 0.8397 0.2965]
 [0.7391 0.4391 0.4739 0.3038 0.7264 0.5336 ... 0.7011 0.2382 0.5189 0.0702 0.4277 0.9248]
 [0.1935 0.6334 0.0941 0.2076 0.2088 0.0456 ... 0.0708 0.7829 0.8226 0.0811 0.6494 0.8591]
 [0.5357 0.7448 0.8294 0.4339 0.8079 0.2576 ... 0.8927 0.7734 0.9116 0.7485 0.4938 0.4701]
 [0.5818 0.6113 0.223  0.8184 0.0866 0.7279 ... 0.009  0.0913 0.7509 0.9023 0.2901 0.363 ]
 [0.7884 0.2622 0.2321 0.4239 0.6157 0.0962 ... 0.4425 0.9831 0.4176 0.465  0.3591 0.4459]
 [0.4524 0.007  0.6095 0.6862 0.1333 0.4956 ... 0.0146 0.8379 0.2579 0.5257 0.5061 0.876 ]]


In [6]:
#help(np.set_printoptions)

## [Vectors](#toc)<a id="vectors"></a>

**In all of engineering calculations use double-precision floating point numeric**

In [7]:
'''Set double precision at creation time'''

x_vec = np.empty(10, dtype=np.float64)

print(type(x_vec))
print(x_vec.dtype)

<class 'numpy.ndarray'>
float64


In [8]:
'''Set double precision after creation'''

x_vec = x_vec.astype(float)
print(type(x_vec))
print(x_vec.dtype)

<class 'numpy.ndarray'>
float64


In [9]:
'''Set single precision after creation; not to be used'''

x_vec = x_vec.astype(np.float32)
print(type(x_vec))
print(x_vec.dtype)

<class 'numpy.ndarray'>
float32


#### [Element-by-element addition/subtraction](#toc)<a id="vecaddsub"></a>

In [10]:
'''Element-by-element addition or subtraction'''

vec1 = np.array(np.random.random(5))
print('vec1     =',vec1)

vec2 = np.array(np.random.random(5))
print('vec2     =',vec2)

result = vec1 + vec2         # element-by-element sum
print('addition   =',result)

result = vec1 - vec2         # element-by-element subtraction
print('difference =',result)

vec1     = [0.0165 0.9699 0.6937 0.9361 0.5884]
vec2     = [0.6966 0.0546 0.1818 0.7058 0.0679]
addition   = [0.7131 1.0245 0.8755 1.642  0.6563]
difference = [-0.6801  0.9153  0.5119  0.2303  0.5204]


#### [Element-by-element product/division](#toc)<a id="vecproddiv"></a>

In [11]:
'''Element-by-element product or division'''

vec1 = np.array(np.random.random(5))
print('vec1    =',vec1)

vec2 = np.array(np.random.random(5))
print('vec2    =',vec2)

result = vec1 * vec2        # element-by-element product
print('product  =',result)

result = vec1 / vec2        # element-by-element division
print('division =',result)

vec1    = [0.6996 0.7875 0.8553 0.1131 0.5181]
vec2    = [0.4321 0.7794 0.0804 0.7784 0.9282]
product  = [0.3023 0.6138 0.0688 0.088  0.4809]
division = [ 1.6189  1.0104 10.6356  0.1453  0.5582]


#### [Self product](#toc)<a id="vecselfprod"></a>

In [12]:
'''Product of all elements of a vector'''

vec1_prod = np.prod(vec1)

print('vec1         =', vec1)
print('vec1 product =', vec1_prod)

vec1         = [0.6996 0.7875 0.8553 0.1131 0.5181]
vec1 product = 0.027610311788138282


#### [Inner product (dot product)](#toc)<a id="vecinnerprod"></a>

The result of the inner product of two vectors: $\vvec_1 \cdot \vvec_2$ is a scalar.

In [13]:
'''Vector inner product or dot product'''

vec1 = np.array(np.random.random(5))
print('vec1           =',vec1)

vec2 = np.array(np.random.random(5))
print('vec2           =',vec2)

result = np.dot(vec1, vec2)     # inner or dot product
print('dot product =',result)

vec1           = [0.2544 0.5823 0.2207 0.3665 0.7789]
vec2           = [0.2431 0.2237 0.5248 0.8438 0.0889]
dot product = 0.6864803739293353


In [14]:
'''More on vector inner product or dot product'''
'''Another way to compute the inner product'''

ele_by_ele_product = vec1 * vec2

inner_product = ele_by_ele_product.sum()

print('vec1 . vec2 = ', inner_product)

vec1 . vec2 =  0.6864803739293351


#### [Scaling (element-by-element multiplication/division by a scalar)](#toc)<a id="vecscale"></a>

In [15]:
'''Scaling of a vector'''

vec = np.array(np.random.random(5))
print('vec    =',vec)

factor = 0.345
scaled = factor * vec     # scaling of vec element-by-element product
print('scaled =', scaled) # assigned to new variable `scaled`

vec *= factor          # in-place scaling
print('vec    =',vec)

vec    = [0.467  0.925  0.5685 0.5274 0.5598]
scaled = [0.1611 0.3191 0.1961 0.1819 0.1931]
vec    = [0.1611 0.3191 0.1961 0.1819 0.1931]


#### [Element-by-element mathematical operations](#toc)<a id="vecops"></a>

In [16]:
'''Mathematical Operations on a Vector'''

vec = np.array(np.random.random(5))
print('vec      =',vec)

log_vec = np.log(vec)         # natural log element-by-element
print('log(vec) =',log_vec)

exp_vec = np.exp(log_vec)     # exponential
print('exp(vec) =',exp_vec)

sin_vec = np.sin(vec)         # sine
print('sin(vec) =',sin_vec)

vec_cubed = vec**3            # powers
print('vec^3    =',vec_cubed)

vec_mean = vec.mean()         # arithmetic mean
print('mean(vec) =',vec_mean)

vec_std = vec.std()           # standard deviation
print('std(vec) =',vec_std)

vec      = [0.4579 0.1331 0.7614 0.5748 0.3385]
log(vec) = [-0.7812 -2.0163 -0.2726 -0.5537 -1.0833]
exp(vec) = [0.4579 0.1331 0.7614 0.5748 0.3385]
sin(vec) = [0.442  0.1328 0.69   0.5437 0.332 ]
vec^3    = [0.096  0.0024 0.4415 0.1899 0.0388]
mean(vec) = 0.4531409073389875
std(vec) = 0.2123262562180827


#### [Element-by-element search](#toc)<a id="vecsearch"></a>

In [17]:
'''Searching a vector for entries matching a test'''

# what are the indices of the values in "vec" that satisfy: vec[] >= 0.3
(idx_ids, ) = np.where(vec >= 0.3) 

print('vec =', vec)
print('indices = ', idx_ids)

vec = [0.4579 0.1331 0.7614 0.5748 0.3385]
indices =  [0 2 3 4]


In [18]:
'''Searching a vector for entries matching a test'''

# what are the indices of the values in "vec" that satisfy: vec[] == 0.3
(idx_ids, ) = np.where(vec == 0.3) 

print('vec =', vec)
print('indices = ', idx_ids)

vec = [0.4579 0.1331 0.7614 0.5748 0.3385]
indices =  []


#### [Zip vectors](#toc)<a id="veczip"></a>

In [19]:
'''Zip creates a list of tuples on the fly'''

print(list(zip(vec1, vec2)))

[(0.25442244665247615, 0.24310767273527567), (0.5822868745614079, 0.22370934526932063), (0.22073707659052255, 0.524771604822689), (0.3665009642517407, 0.8438148659312172), (0.7788812934788941, 0.08893498689070856)]


## [Matrices](#toc)<a id="matrices"></a>

**In all of engineering calculations use double-precision floating point numeric**

In [20]:
'''Set double precision at creation time'''

mtrx = np.empty((5,5), dtype=np.float64)

print(type(mtrx))
print(mtrx.dtype)

<class 'numpy.ndarray'>
float64


In [21]:
'''Set double precision after creation'''

mtrx = mtrx.astype(float)

print(type(mtrx))
print(mtrx.dtype)

<class 'numpy.ndarray'>
float64


#### [Element-by-element addition/subtraction](#toc)<a id="mataddsub"></a>

In [22]:
'''Element-by-element addition or subtraction'''

mat1 = np.random.random((3,3))
print('mat1       =\n', mat1)

mat2 = np.random.random((3,3))
print('mat2       =\n', mat2)

result = mat1 + mat2              # element-by-element sum
print('addition   =\n', result)

result = mat1 - mat2              # element-by-element subtraction
print('difference =\n', result)

mat1       =
 [[0.4256 0.0636 0.943 ]
 [0.2789 0.4567 0.9803]
 [0.5306 0.3609 0.6517]]
mat2       =
 [[0.0839 0.6742 0.4054]
 [0.1058 0.0978 0.5154]
 [0.596  0.9449 0.4409]]
addition   =
 [[0.5096 0.7378 1.3484]
 [0.3847 0.5546 1.4957]
 [1.1266 1.3058 1.0926]]
difference =
 [[ 0.3417 -0.6106  0.5375]
 [ 0.1731  0.3589  0.4649]
 [-0.0654 -0.5839  0.2108]]


#### [Element-by-element product/division](#toc)<a id="matproddiv"></a>

In [23]:
'''Element-by-element product or division'''

mat1 = np.random.random((3,3))
print('mat1     =\n', mat1)

mat2 = np.random.random((3,3))
print('mat2     =\n', mat2)

result = mat1 * mat2          # element-by-element product
print('product  =\n', result)

result = mat1 / mat2          # element-by-element division (cross your fingers)
print('division =\n', result)

mat1     =
 [[0.3583 0.2366 0.5308]
 [0.3477 0.0318 0.4262]
 [0.0421 0.2821 0.8018]]
mat2     =
 [[0.6029 0.2993 0.8766]
 [0.5315 0.2975 0.9084]
 [0.1141 0.2545 0.6539]]
product  =
 [[0.216  0.0708 0.4653]
 [0.1848 0.0095 0.3872]
 [0.0048 0.0718 0.5243]]
division =
 [[0.5943 0.7905 0.6055]
 [0.6542 0.107  0.4692]
 [0.3692 1.1084 1.2261]]


In [ ]:
'''Produce Noise on a Matrix Image (brick data)'''

from matplotlib import pyplot as plt     # import the pyplot function of the matplotlib package
#%matplotlib inline
plt.rcParams['figure.figsize'] = [20, 4] # extend the figure size on screen output

# Read image from the images/ directory in the chen-3170 repo
block = plt.imread('images/glacier.png', format='png')

plt.figure(1)
plt.imshow(block)
plt.title('Matrix Reloaded', fontsize=14)
plt.show()
print('block shape =', block.shape)  # inspect the array shape

In [ ]:
'''Use Matrix Element-by-Element Multiplication'''

mtrx_shape = block.shape[0:2]                 # use the shape to automate noise_mtrx generation

noise_mtrx = np.random.random(mtrx_shape)   # generate random matrix

block_noise = block[:,:,2] * noise_mtrx   # apply noise to the blue channel

plt.figure(2)
plt.imshow(block_noise, cmap='gray')
plt.title('Noisy Block',fontsize=14)
plt.show()

In [ ]:
'''Matrix Scaling (matrix product or division by a scalar)'''

mat1 = np.random.random((3,3))
print('mat1      =\n',mat1)

factor = 3.21
result = factor * mat1        # scaling of mat1 element-by-element; product with factor
print('scaled   =\n',result)

#### [Scaling (element-by-element multiplication/division by a scalar)](#toc)<a id="matscale"></a>

In [ ]:
'''Matrix Scaling of an Image'''

color_channel = np.copy(block[:,:,0])   # copy the red channel

color_channel /= color_channel.max()    # scale to gray, 0-255 values
color_channel *= 255
gray_channel  = color_channel.astype(int) # truncate all float data type to int

plt.figure(3)
plt.imshow(gray_channel, cmap='gray')
#plt.imshow(gray_channel)

plt.title('Matrix Gray Scaling',fontsize=14)
plt.show()

#### [Element-by-element mathematical operations](#toc)<a id="matops"></a>

In [ ]:
'''Other Mathematical Operations on a Matrix'''

mtrx = np.copy(block[:,:,0])    # copy the red channel

plt.figure(4)
plt.imshow(mtrx, cmap='gray')              # show channel as a flat image with default colormap
plt.title('Original', fontsize=14)
plt.show()

mtrx_mean = mtrx.mean()         # arithmetic mean
print('mean(mtrx) =', mtrx_mean)

mtrx_std = mtrx.std()           # standard deviation
print('std(mtrx) =', mtrx_std)

In [ ]:
'''Other Mathematical Operations on a Matrix'''

log_mtrx = np.log(mtrx + .001)  # natural log element-by-element

plt.figure(5)
plt.imshow(log_mtrx, cmap='gray')
plt.title('Log Transform', fontsize=14)
plt.show()

mtrx_mean = log_mtrx.mean()         # arithmetic mean
print('mean(mtrx) =', mtrx_mean)

mtrx_std = log_mtrx.std()           # standard deviation
print('std(mtrx) =', mtrx_std)

In [ ]:
'''Other Mathematical Operations on a Matrix'''

exp_mtrx = np.exp(log_mtrx)     # exponential

plt.figure(6)
plt.imshow(exp_mtrx)
plt.title('Exp of Log Transform', fontsize=14)
plt.show()

mtrx_mean = exp_mtrx.mean()         # arithmetic mean
print('mean(mtrx) =', mtrx_mean)

mtrx_std = exp_mtrx.std()           # standard deviation
print('std(mtrx) =', mtrx_std)

In [ ]:
'''Other Mathematical Operations on a Matrix'''

sin_mtrx = np.sin(mtrx + np.pi/2)  # sine

plt.figure(7)
plt.imshow(sin_mtrx)
plt.title('Sine Transform', fontsize=14)
plt.show()

mtrx_mean = sin_mtrx.mean()         # arithmetic mean
print('mean(mtrx) =', mtrx_mean)

mtrx_std = sin_mtrx.std()           # standard deviation
print('std(mtrx) =', mtrx_std)

In [ ]:
'''Other Mathematical Operations on a Matrix'''

mtrx_cubed = mtrx**3  # powers

plt.figure(8)
plt.imshow(mtrx_cubed, cmap='gray')
plt.title('Cube Transform', fontsize=14)
plt.show()

mtrx_mean = mtrx_cubed.mean()         # arithmetic mean
print('mean(mtrx) =', mtrx_mean)

mtrx_std = mtrx_cubed.std()           # standard deviation
print('std(mtrx) =', mtrx_std)

#### [Transposition](#toc)<a id="mattransp"></a>

In [ ]:
'''Matrix Transposition'''
'''clockwise rotation followed by horizontal right to left flip'''

mtrx = np.random.random((5,7))

np.set_printoptions(precision=3,threshold=20,edgeitems=12,linewidth=100) # one way to control printing of numpy arrays

print('mtrx =\n',mtrx)

mtrx_T = mtrx.transpose()       # transpose of a mtrx: M[i,j] -> M[j,i]

print('mtrx^T =\n',mtrx_T)

In [ ]:
'''Matrix Transposition'''
'''Example of adding a transformed matrix to another transform transposed'''

'''note: to add a matrix to its transpose, a matrix must be square'''

n_rows = block.shape[0]
n_columns = n_rows

mtrx = np.copy(block[:n_rows,:n_columns,0])   # select a square block; red channel

sin_mtrx = np.sin(mtrx + np.pi/2)  # sine

sin_mtrx /= sin_mtrx.max()
plt.figure(9)
plt.imshow(sin_mtrx)
plt.title('Sine Transform', fontsize=14)
plt.show()

mtrx_cubed = mtrx**3                # powers

plt.figure(10)
plt.imshow(mtrx_cubed)
plt.title('Cube Transform', fontsize=14)
plt.show()

plt.figure(11)
plt.imshow(sin_mtrx + mtrx_cubed.transpose())    # sine + cubed transposed
plt.title('Sine + Cube Transpose Transform', fontsize=14)
plt.show()

#### [Element-by-element search](#toc)<a id="matsearch"></a>

In [ ]:
'''Searching a matrix for entries matching a test'''

# what are the indices of the values in "mtrx" that satisfy: mtrx >= 0.3
(idx_ids, jdx_ids) = np.where(mtrx >= 0.3) 

np.set_printoptions(precision=3, threshold=20, edgeitems=5, linewidth=100) 

print('matrix =\n', mtrx)
print('ith indices = ',idx_ids)
print('jth indices = ',jdx_ids)

In [ ]:
'''Verify the searched elements'''

mtrx[idx_ids, jdx_ids].min()

In [ ]:
mtrx[idx_ids, jdx_ids].shape

In [ ]:
mtrx[idx_ids, jdx_ids].dtype