ChEn-3170: Computational Methods in Chemical Engineering Fall 2021 UMass Lowell; Prof. V. F. de Almeida **13Sep21**

# 05. Basic Flow Controls in Python
$  
  \newcommand{\Amtrx}{\boldsymbol{\mathsf{A}}}
  \newcommand{\Bmtrx}{\boldsymbol{\mathsf{B}}}
  \newcommand{\Mmtrx}{\boldsymbol{\mathsf{M}}}
  \newcommand{\Imtrx}{\boldsymbol{\mathsf{I}}}
  \newcommand{\Pmtrx}{\boldsymbol{\mathsf{P}}}
  \newcommand{\Lmtrx}{\boldsymbol{\mathsf{L}}}
  \newcommand{\Umtrx}{\boldsymbol{\mathsf{U}}}
  \newcommand{\xvec}{\boldsymbol{\mathsf{x}}}
  \newcommand{\avec}{\boldsymbol{\mathsf{a}}}
  \newcommand{\bvec}{\boldsymbol{\mathsf{b}}}
  \newcommand{\cvec}{\boldsymbol{\mathsf{c}}}
  \newcommand{\zerovec}{\boldsymbol{\mathsf{0}}}
  \newcommand{\rvec}{\boldsymbol{\mathsf{r}}}
  \newcommand{\norm}[1]{\bigl\lVert{#1}\bigr\rVert}
  \DeclareMathOperator{\rank}{rank}
$

---
## Table of Contents<a id="toc">
* [Objectives](#obj)
* [Modules](#modules)
* [Conditionals](#conditionals)
 + [Assert](#assert)
 + [If](#if)
* [Loops](#loops)
 + [For](#for)
 + [While](#while)
 + [List comprehension](#listcomp)
* [Functions](#functions)
 + [Example:](#get_triangular_matrix) get triangular matrix
 + [Example:](#forward_solve) foward substitution solve
* [Input/Output](#io)
 + [Read "text"](#itext)
---

## [Objectives](#toc)<a id="obj"></a>

 + Describe a variety of controls used to manipulate the execution of a Python program in this course.

## [Modules](#toc)<a id="modules"></a>
We have been using `import` packages into the Python notebook (*e.g* `import numpy as np`). We can use this to simplify our future coding experience and accelerate learning. For instance, we can use import of our own codes. In this course a directory named `chen_3170` was created in the [repository](https://github.com/dpploy/chen-3170) file system to store course-related Python code. The syntax to import codes in the repository is as follows:

In [ ]:
'''To view what is available'''

import chen_3170

help(chen_3170)

In [ ]:
'''Check individual packages'''

import chen_3170.help

help(chen_3170.help)

In [ ]:
'''Import the get_triangular_matrix function'''

from chen_3170.help import get_triangular_matrix

help(get_triangular_matrix)

In [ ]:
'''Practice using the function'''

a_mtrx = get_triangular_matrix('lower',5) # lower triangular random matrix 5 x 5
print('a_mtrx =\n',a_mtrx)

a_mtrx = get_triangular_matrix('upper',5) # upper triangular random matrix 5 x 5
print('a_mtrx =\n',a_mtrx)

import numpy as np
ones_mtrx = np.ones((5,5))
print('ones_mtrx =\n',ones_mtrx)

a_mtrx = get_triangular_matrix('lower', mtrx=ones_mtrx)
print('a_mtrx =\n',a_mtrx)

<div class="alert alert-block alert-warning">
The source code should be inspected for correctness and as a source of information for future programing. This is how the source code can be viewed and copied into a notebook cell.
</div>

In [ ]:
'''View the source code in the notebook'''

# This command does not work on Windows (the source code is provide below in any case)
!cat "chen_3170/help.py" # ugly but works for now

# This command seems to work on Windows (uncomment the next line)
#!type "chen_3170\help.py"

Copying the source code to this cell and rendering it with code block fences gives:

```python
def get_triangular_matrix( mode='lower', ndim=None, mtrx=None ):
    '''
    Returns a triangular matrix in-place.

    If a matrix is given, the function will modify the input, in place, into a 
    triangular matrix. The mtrx object will be modified and reflected on the callee side.
    Otherwise, the function generates a random triangular matrix.

    Parameters
    ----------
    mode: string, optional
          Type of triangular matrix: 'lower' or 'upper'. Defaults to lower 
          triangular.
    ndim: int, optional
          Dimension of the square matrix. If a matrix is not provided this 
          argument is required. 
    mtrx: numpy.ndarray, optional
          square matrix to be turned into a triangular matrix.
    
    Returns
    -------
    mtrx: numpy.ndarray
          If a matrix was not passed the return is random array. If a matrix
          was passed, its view is modified.

    Examples
    --------

    >>> a_mtrx = ce.get_triangular_matrx('lower',3)
    >>> a_mtrx
    array([[0.38819556, 0.    , 0.        ],
       [0.12304746, 0.07522054, 0.        ],
       [0.96357929, 0.69187941, 0.2878785 ]])

    '''

    assert ndim is None or mtrx is None, 'ndim or mtrx must be given; not both.'
    assert not (ndim is None and mtrx is None), 'either ndim or mtrx must be given.'
    assert mode =='lower' or mode =='upper', 'invalid mode %r.'%mode
    
    if mtrx is None:
        import numpy as np
        mtrx = np.random.random((ndim,ndim))
    else:
        assert mtrx.shape[0] == mtrx.shape[1], 'matrix not square.' 
    
    # ready to return matrix  
    if mode == 'lower':
        for i in range(mtrx.shape[0]):
            mtrx[i,i+1:] = 0.0
    elif mode == 'upper':
        for j in range(mtrx.shape[1]):
            mtrx[j+1:,j] = 0.0
    else:
        assert False, 'oops. something is very wrong.'

    return mtrx      
```

## [Conditionals](#toc)<a id="conditionals"></a>
Constructs that allow branching of operations. The most importants are:
 1. `assert` statement
 1. `if` statement

### [`Assert` statement](#toc)<a id="assert"></a>
The general format is:
```python
    assert test, string(formatted)
```
and it tests for whether `test` is `True`.

### Examples
```python
    assert ndim is None or mtrx is None, 'ndim or mtrx must be given; not both.'
    assert not (ndim is None and mtrx is None), 'either ndim or mtrx must be given.'
    assert mode =='lower' or mode =='upper', 'invalid mode %r.'%mode
```

In [ ]:
'''Testing example'''

import numpy as np

ndim = None
#ndim = 1  # uncomment for failing assert
mtrx = np.random.random((3,4))

assert ndim is None or mtrx is None, 'either ndim or mtrx must be given; not both'

#mtrx = None
assert not (ndim is None and mtrx is None), 'either ndim or mtrx must be given; ndim = %r; mtrx = %r.'%(ndim, mtrx)

In [ ]:
'''Testing example'''

import numpy as np

mode = 'lower'
#mode = 'dontknow' # uncomment for a failing assert

assert mode == 'lower' or mode == 'upper', 'invalid mode: %r.'%mode

### [`If` statement](#toc)<a id='if'></a>
The general format is:
```python
if test1:        # if test
    statements1  # associated block
elif test2:      # optional elifs
    statements2
elif test3:      # more optional elifs etc.
    statements3
else:            # optional final else
    statements4
    
# continue normal flow from here
```

### Example
If-else example:
```python
    if mtrx is None:      # test if mtrx has type None
        import numpy as np
        mtrx = np.random.random((n,n))  # associated block
    else:                 # final test
        assert mtrx.shape[0] == mtrx.shape[1] # l_mtrx must be square
```

In [7]:
'''Testing example'''

test = 1 # change this to 1, 2 or 3

# test setup (uses multiway branching)
if test == 1:
    mtrx = None
    n = 4    
elif test == 2:
    import numpy as np
    mtrx = np.array( [ [3.4, 2.1, 4.5],
                       [0.0, 2.0, 1.0] 
                     ] )
elif test == 3:
    import numpy as np
    mtrx = np.array( [ [ 3.4,  2.1,  4.5],
                       [ 0.0,  2.0,  1.0],
                       [-1.0, -3.0, -5.0]
                     ] )
else:
    assert False, 'test must be 1, 2, or 3.'

# What we are really testing
#---------------------------------------------------------------    
if mtrx is None:      # test if mtrx has type None
    import numpy as np
    mtrx = np.random.random((n,n))  # associated block
else:                 # final test
    assert mtrx.shape[0] == mtrx.shape[1],'matrix not square.'
#---------------------------------------------------------------
    
print(mtrx)

[[0.80892371 0.94363397 0.79920228 0.41696567]
 [0.58305036 0.26973267 0.97208831 0.53558601]
 [0.44411428 0.88410596 0.67854862 0.04573088]
 [0.76803461 0.72937267 0.0242252  0.86829291]]


### Example
Multiway branching example:
```python
    # ready to return matrix  
    if mode == 'lower':                 # test if mode is 'lower'
        for i in range(mtrx.shape[0]):  # associated block of statements
            mtrx[i,i+1:] = 0.0
    elif mode == 'upper':               # test if mode is 'upper'
        for j in range(mtrx.shape[1]):  # associated block of statements
            mtrx[j+1:,j] = 0.0
    else:                               # final test
        assert False, 'mode must be either lower or upper.' # associated block
```

In [10]:
'''Testing example'''

import numpy as np
test = 1 # change this to 1 or 2

mtrx = np.array([[ 3.4,  2.1,  4.5],
                 [ 0.0,  2.0,  1.0],
                 [-1.0, -3.0, -5.0]
                ])
# test setup (uses multiway branching)
if test == 1:
    mode = 'lower'
elif test == 2:
    mode = 'upper'
else:
    assert False,'test must be 1 or 2.'
    
# What we are really testing
#---------------------------------------------------------------    
# ready to return matrix  
if mode == 'lower':                 # test if mode is 'lower'
    for i in range(mtrx.shape[0]):  # associated block of statements
            mtrx[i,i+1:] = 0.0
elif mode == 'upper':               # test if mode is 'upper'
    for j in range(mtrx.shape[1]):  # associated block of statements
        mtrx[j+1:,j] = 0.0
else:                               # final test
    assert False, 'mode must be either "lower" or "upper"' # associated block
#---------------------------------------------------------------
    
print(mtrx)

AssertionError: test must be 1 or 2.

## [Loops](#toc)<a id="loops"></a>
Contructs that allow repetitive actions on data. There are two basic types: 
 1. `for` loops
 2. `while` loops

### [`For` loops](#toc)<a id='for'></a>

The general format is (**indentation is mandatory**):

```python
for `target` in `object`: # assign object items to target
    
    `statements`      # repeated loop body: (possibly) use target
    
    if test1: 
        break         # exit loop now; skip else
    if test2: 
        continue      # go to top of the loop now
        
else:                 # optional else part
    statements        # if did not hit a `break`
```

### Example
```python
for i in range(mtrx.shape[0]): # assign i to objects in range(mtrx.shape[0])
    mtrx[i, i+1:] = 0.0         # loop over this statement with varying i
```

In [1]:
'''Testing example'''

import numpy as np

mtrx = np.random.random((5,5))
print(mtrx)

m_rows = mtrx.shape[0]

for i in range(m_rows):  # assign i to objects in range(m_rows)
    print('i =',i)
    mtrx[i,i+1:] = 0.0  # for each row, zero out columns to the right of the main diagonal
    
print(mtrx)

[[0.9865091  0.75144016 0.01919364 0.12075936 0.40293032]
 [0.59015868 0.02478706 0.34314311 0.06164204 0.48705058]
 [0.8306934  0.0219869  0.75057438 0.45451769 0.45317303]
 [0.51337865 0.11583982 0.24317923 0.94604691 0.58761815]
 [0.1733699  0.69180636 0.8887007  0.9021204  0.18497599]]
i = 0
i = 1
i = 2
i = 3
i = 4
[[0.9865091  0.         0.         0.         0.        ]
 [0.59015868 0.02478706 0.         0.         0.        ]
 [0.8306934  0.0219869  0.75057438 0.         0.        ]
 [0.51337865 0.11583982 0.24317923 0.94604691 0.        ]
 [0.1733699  0.69180636 0.8887007  0.9021204  0.18497599]]


In [2]:
'''Example with Continue'''

for i in range(10):
    
    if i == 5:
        continue # go to the top of the loop now
    else:
        print(i)

0
1
2
3
4
6
7
8
9


### [`While` loops](#toc)<a id="while"></a>

The general format is:

```python
    while `test` :
        
        `statments` # loop over the body of statements as long as `test` is true
```

### Example

```python
    while (abs(delta_k) > tolerance or abs(f_k) > tolerance) and k <= k_max:
        
        # body
        
        f_k       = f_eq( ext_hat, x_a_0, x_b_0, x_c_0, eq_kx_cte )
        f_prime_k = f_eq_prime( ext_hat, x_c_0, eq_kx_cte )
        
        delta_k_old = delta_k
        delta_k = -f_k / f_prime_k
        
        ext_hat += delta_k
        
        if k > 0:
            if delta_k != 0.0 and delta_k_old != 0.0:
                convergence_factor = math.log(abs(delta_k),10) / math.log(abs(delta_k_old),10)
            else:
                convergence_factor = 0.0  
        else:
            convergence_factor = 0.0
            
        k = k + 1
        
        if verbose is True:
            print('%2i %+5.3e %+5.3e %+5.3e  %+5.3e %5.2f'%\
                  (k,f_k,f_prime_k,abs(delta_k),ext_hat,convergence_factor))
            
        # ends by indentation
```

In [ ]:
'''While example'''

k_max = 9
k = 0

while k <= k_max:
    
    print('k =',k)
    k += 1

### [List Comprehension](#toc)<a id="listcomp"></a>
A list comprehension is simple way to build a for loop inside a Python list. For example:

```python
[i for i in range(10)]
```

In [ ]:
'''List Comprehension'''

[i for i in range(10)]

In [ ]:
'''List Comprehension'''

[i for i in range(10)]

## [Functions](#toc)<a id="functions"></a>
In simple terms, functions are an efficient alternative to *cutting and pasting* code. They increase code reuse, allow for modularity, and are indispensible to software/code design. An initial format of the functions we will use is:
```python
def function_name(param1, param2,..., paramN):
    statements
    ...
    statements
    return result # optional but almost always present
```
The function block has its own scope and no variable name is accessible inside the function unless it is passed through the argument list.

How to use a function with 2 parameters in a Jupyter Notebook cell:

```python
a_param = 10
b_param = 'hello'
c_result = function_name(a_param, b_param)
```

### [Example: get triangular matrix](#toc)<a id="get_triangular_matrix"></a>
```python
def get_triangular_matrix(mode='lower', ndim=None, mtrx=None):

    assert ndim is None or mtrx is None, 'ndim or mtrx must be given; not both.'
    assert mode =='lower' or mode =='upper', 'invalid mode %r.'%mode
    
    if mtrx is None:
        import numpy as np
        mtrx = np.random.random((ndim,ndim))
    else:
        assert mtrx.shape[0] == mtrx.shape[1], 'matrix not square.' 
    
    # ready to return matrix  
    if mode == 'lower':
        for i in range(mtrx.shape[0]):
            mtrx[i,i+1:] = 0.0
    elif mode == 'upper':
        for j in range(mtrx.shape[1]):
            mtrx[j+1:,j] = 0.0
    else:
        assert False, 'mode must be either lower or upper.'
        
    return mtrx     
```

In [ ]:
'''Import module'''

from chen_3170.help import get_triangular_matrix

help(get_triangular_matrix)

In [ ]:
'''Testing the example'''

import numpy as np
np.set_printoptions(precision=3) 

# no arguments will fail
#a_mtrx = get_triangular_matrix()

In [ ]:
'''Testing the example'''

# one-argument call
size = 5
out_mtrx = get_triangular_matrix(ndim=size)

print('out_mtrx =\n', out_mtrx)

In [ ]:
'''Testing the example'''

# one-argument call
in_mtrx = np.random.random((size,size))

out_mtrx = get_triangular_matrix(mtrx=in_mtrx)

print('out_mtrx =\n',out_mtrx)

In [ ]:
'''Testing the example'''

# two-argument conflicting call will fail

#out_mtrx = get_triangular_matrix(ndim=size, mtrx=in_mtrx) # uncomment to test

In [ ]:
'''Testing the example'''

# passing argument by object reference
in_mtrx = np.random.random((size,size))
print('in_mtrx before =\n',in_mtrx)

out_mtrx = get_triangular_matrix(mtrx=in_mtrx) # now out_mtrx is a view of in_mtrx

print('in_mtrx after =\n',in_mtrx)
print('out_mtrx =\n',out_mtrx)

### [Example: forward substitution solve](#toc)<a id="forward_solve"></a>
 + Import module as described [before.](#modules)
 + `!cat` the `chen_3170/help.py` file to get the source code for the `forward_solve` function. Then copy into the a markdown cell and add a code fence block to display the source code.

In [ ]:
'''Import module'''

from chen_3170.help import forward_solve

help(forward_solve)

In [ ]:
'''View the source code in the notebook'''

!cat "chen_3170/help.py" # ugly but works for now

```python
 def forward_solve(l_mtrx, b_vec, loop_option='use-dot-product'):
    """Performs a forward solve with a lower triangular matrix and right side vector.
    
    Parameters
    ----------
    l_mtrx: numpy.ndarray, required
            Lower triangular matrix.
    b_vec:  numpy.ndarray, required
            Right-side vector.
    loop_option: string, optional
            This is an internal option to demonstrate the usage of an explicit 
            double loop or an implicit loop using a dot product. 
            Default: 'use-dot-product'
            
    Returns
    -------
    x_vec: numpy.narray
           Solution vector returned.
           
    Examples
    --------
    
    """        
    import numpy as np
    
    # sanity test
    assert isinstance(l_mtrx,np.ndarray)      # l_mtrx must be np.ndarray
    assert l_mtrx.shape[0] == l_mtrx.shape[1],'non-square matrix.' # l_mtrx must be square
    assert np.all(np.abs(np.diagonal(l_mtrx)) > 0.0),'zero value on diagonal.'
    rows_ids, cols_ids = np.where(np.abs(l_mtrx) > 0) # get i, j of non zero entries
    assert np.all(rows_ids >= cols_ids),'non-triangular matrix.' # test i >= j
    assert b_vec.shape[0] == l_mtrx.shape[0],'incompatible l_mtrx @ b_vec dimensions'  # b_vec must be compatible to l_mtrx
    assert loop_option == 'use-dot-product' or loop_option == 'use-double-loop'
    # end of sanity test
    
    m_rows = l_mtrx.shape[0]
    n_cols = m_rows
    x_vec = np.zeros(n_cols)
    
    if loop_option == 'use-dot-product':
        
        for i in range(m_rows):
            sum_lx = np.dot( l_mtrx[i,:i], x_vec[:i] )
            #sum_lx = l_mtrx[i,:i] @ x_vec[:i] # matrix-vec mult. alternative to dot product
            x_vec[i] = (b_vec[i] - sum_lx)/l_mtrx[i,i]
            
    elif loop_option == 'use-double-loop':
             
        for i in range(m_rows):
            sum_lx = 0.0
            for j in range(i):
                sum_lx += l_mtrx[i,j] * x_vec[j]
            x_vec[i] = (b_vec[i] - sum_lx)/l_mtrx[i,i]
               
    else:
        assert False, 'not allowed option: %r'%loop_option
        
    return x_vec  
```

A lower triangular matrix allows for a forward solve.
The algorithm for $\Lmtrx\,\xvec=\bvec$ is as follows: 

\begin{equation*}
x_i = \Bigl(b_i - \sum\limits_{j=1}^{i-1} L_{i,j}\,x_j \Bigr)\,L^{-1}_{i,i} \quad\ \forall \quad\ i=1,\ldots,m
\end{equation*}

**for $i$ and $j$ with offset 1**. Recall that `NumPy` and `Python` have offset 0 for their sequence data types.

In [ ]:
'''Testing the example'''

import numpy as np

size = 5

l_mtrx = get_triangular_matrix(ndim=size)

b_vec  = np.random.random(size)

x_vec  = forward_solve(l_mtrx, b_vec, loop_option='use-double-loop')

np.set_printoptions(precision=3)
print('l_mtrx=\n',l_mtrx)
print('b_vec=',b_vec)
print('x_vec =',x_vec)

In [ ]:
'''Testing the example'''

# rectangular matrix fails
l_mtrx = np.ones((size,size+1))

b_vec  = np.random.random(size)

#x_vec = forward_solve(l_mtrx, b_vec) # uncomment to fail

In [ ]:
'''Testing the example'''

# zero element on diagonal matrix fails
l_mtrx = get_triangular_matrix(ndim=size)

l_mtrx[size-1,size-1] = 0.0

b_vec  = np.random.random(size)

#x_vec = forward_solve(l_mtrx, b_vec) # uncomment to fail

## [Input/Output](#toc)<a id="io"></a>
Reading and writing data to persistent storage is needed so that external data is used in a python program or data is saved to disk for future use. This section will list IO operations used in this course. A file is a storage compartment managed by the underlying operating system. Access these files is provided in Python through the built-in function `open` that creates a file object. Using this file object and its methods, data can be transferred in and out of a Python program.
The general format of `open` is:
```python
import io                   # import io module
file = open(filename, mode) # create file object
file.method_name_example()  # use a file method of some name
```

### [Read "text"](#toc)<a id="itext"></a>

<div class="alert alert-block alert-info">
This is often referred to as reading formated ASCII data from a file. Simply put, if the file can be displayed with a common text editor, the data is in ASCII format. For example the (partial heptane combustion reaction mechanism) file in the course repository `data/`: [rxn-mech.txt](https://github.com/dpploy/chen-3170/blob/master/data/rxn-mech.txt).
<p>
Reading text in Python will always result into a string type.
</p>
</div>

In [ ]:
'''Open file (heptane combustion (incomplete))'''

import io

# open file in reading mode 'r' (default), text 't' (default)

file = open('data/n-heptane-rxn.txt', 'rt')

print(type(file))

In [ ]:
'''Help on open'''

#help(open)

In [ ]:
'''Methods of finput = open()'''

#dir(file)

In [ ]:
'''Example of a read method finput.read()'''

help(file.read)

In [ ]:
'''Let's peek into the file'''

!cat 'data/n-heptane-rxn.txt'

In [ ]:
'''Minimalist approach'''

# do nothing (i.e. no direct method) just iterate on the file

for line in file:
    print('line =', line) # the line object has an `end of line` character

In [ ]:
'''Artifact in reading text'''

print(type(line))
print('line =',line)
print('chars =', [i for i in line]) # inspect character by character

In [ ]:
'''Removing artifact'''

reactions = list() # empty list

reactions.append(line.strip()) # leading and trailing spaces; remove end of line special character \n
print('reaction =', reactions) 
print('chars =', [i for i in reactions[0]])

In [ ]:
'''Manipulate reactions'''

print('split = ',reactions[0].split('<') )

left = reactions[0].split('<')[0] # reactants
print('left side =',left)

print('split =',reactions[0].split('>'))

right = reactions[0].split('>')[1] # products
print('right side =',right)

In [ ]:
'''Manipulate species'''

species = left.split('+') + right.split('+')
print('species =',species)

In [ ]:
'''Clean up species'''

[spc.strip() for spc in species]

In [ ]:
'''Close the file'''

file.close() # close the file