ChEn-3170: Computational Methods in Chemical Engineering Spring 2020 UMass Lowell; Prof. V. F. de Almeida **28Jan20**

# 05. Basic Flow Controls in Python
$  
  \newcommand{\Amtrx}{\boldsymbol{\mathsf{A}}}
  \newcommand{\Bmtrx}{\boldsymbol{\mathsf{B}}}
  \newcommand{\Mmtrx}{\boldsymbol{\mathsf{M}}}
  \newcommand{\Imtrx}{\boldsymbol{\mathsf{I}}}
  \newcommand{\Pmtrx}{\boldsymbol{\mathsf{P}}}
  \newcommand{\Lmtrx}{\boldsymbol{\mathsf{L}}}
  \newcommand{\Umtrx}{\boldsymbol{\mathsf{U}}}
  \newcommand{\xvec}{\boldsymbol{\mathsf{x}}}
  \newcommand{\avec}{\boldsymbol{\mathsf{a}}}
  \newcommand{\bvec}{\boldsymbol{\mathsf{b}}}
  \newcommand{\cvec}{\boldsymbol{\mathsf{c}}}
  \newcommand{\rvec}{\boldsymbol{\mathsf{r}}}
  \newcommand{\norm}[1]{\bigl\lVert{#1}\bigr\rVert}
  \DeclareMathOperator{\rank}{rank}
$

---
## Table of Contents
* [Objectives](#obj)
* [Modules](#modules)
* [Conditionals](#conditionals)
 + [Assert](#assert)
 + [If](#if)
* [Loops](#loops)
 + [For](#for)
 + [While](#while)
* [Functions](#functions)
 + [Example:](#get_triangular_matrix) get triangular matrix
 + [Example:](#forward_solve) foward substitution solve
* [Input/Output](#io)
 + [Read "text"](#itext)
---

## Objectives<a id="obj"></a>

 + Describe a variety of controls used to manipulate the execution of a Python program in this course.

## Modules<a id="modules"></a>
We have been using `import` packages into the Python notebook (*e.g* `import numpy as np`). We can use this to simplify our future coding experience and accelerate learning. For instance, we can use import of our own codes. In this course a directory named `chen_3170` was created in the [repository](https://github.com/dpploy/chen-3170) file system to store course-related Python code. The syntax to import codes in the repository is as follows:

In [1]:
'''To view what is available'''

import chen_3170
help(chen_3170)

Help on package chen_3170:

NAME
    chen_3170

PACKAGE CONTENTS
    help
    toolkit

FILE
    (built-in)




In [ ]:
'''Check individual packages'''

import chen_3170.help
help(chen_3170.help)

In [3]:
'''Import the get_triangular_matrix function'''

from chen_3170.help import get_triangular_matrix

help(get_triangular_matrix)

Help on function get_triangular_matrix in module chen_3170.help:

get_triangular_matrix(mode='lower', ndim=None, mtrx=None)
    Returns a triangular matrix in-place.
    
    If a matrix is given, the function will modify the input, in place, into a
    triangular matrix. The mtrx object will be modified and reflected on the callee side.
    Otherwise, the function generates a random triangular matrix.
    
    Parameters
    ----------
    mode: string, optional
          Type of triangular matrix: 'lower' or 'upper'. Defaults to lower
          triangular.
    ndim: int, optional
          Dimension of the square matrix. If a matrix is not provided this
          argument is required.
    mtrx: numpy.ndarray, optional
          square matrix to be turned into a triangular matrix.
    
    Returns
    -------
    mtrx: numpy.ndarray
          If a matrix was not passed the return is random array. If a matrix
          was passed, its view is modified.
    
    Examples
    --------
  

In [4]:
'''Practice using the function'''

a_mtrx = get_triangular_matrix('lower',5) # lower triangular random matrix 5 x 5
print('a_mtrx =\n',a_mtrx)

a_mtrx = get_triangular_matrix('upper',5) # upper triangular random matrix 5 x 5
print('a_mtrx =\n',a_mtrx)

import numpy as np
ones_mtrx = np.ones((5,5))
print('ones_mtrx =\n',ones_mtrx)

a_mtrx = get_triangular_matrix('lower',mtrx=ones_mtrx)
print('a_mtrx =\n',a_mtrx)

a_mtrx =
 [[0.32029876 0.         0.         0.         0.        ]
 [0.49546519 0.24867136 0.         0.         0.        ]
 [0.15278621 0.36610871 0.87843842 0.         0.        ]
 [0.84516433 0.41680356 0.04559272 0.28946761 0.        ]
 [0.78632449 0.93927484 0.73786317 0.67800487 0.64362929]]
a_mtrx =
 [[0.80322014 0.40249634 0.07637611 0.64723307 0.37130466]
 [0.         0.39341604 0.80881303 0.60222004 0.51334212]
 [0.         0.         0.94334123 0.26614127 0.10038501]
 [0.         0.         0.         0.23777117 0.75575458]
 [0.         0.         0.         0.         0.01170546]]
ones_mtrx =
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
a_mtrx =
 [[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


<div class="alert alert-block alert-warning">
The source code should be inspected for correctness and as a source of information for future programing. This is how the source code can be viewed and copied to a notebook cell.
</div>

In [ ]:
'''View the source code in the notebook'''

!cat "chen_3170/help.py" # ugly but works for now

Copying the source code to this cell and rendering it with code fences gives:

```python
def get_triangular_matrix( mode='lower', ndim=None, mtrx=None ):
    '''
    Returns a triangular matrix in-place.

    If a matrix is given, the function will modify the input, in place, into a 
    triangular matrix. The mtrx object will be modified and reflected on the callee side.
    Otherwise, the function generates a random triangular matrix.

    Parameters
    ----------
    mode: string, optional
          Type of triangular matrix: 'lower' or 'upper'. Defaults to lower 
          triangular.
    ndim: int, optional
          Dimension of the square matrix. If a matrix is not provided this 
          argument is required. 
    mtrx: numpy.ndarray, optional
          square matrix to be turned into a triangular matrix.
    
    Returns
    -------
    mtrx: numpy.ndarray
          If a matrix was not passed the return is random array. If a matrix
          was passed, its view is modified.

    Examples
    --------

    >>> a_mtrx = ce.get_triangular_matrx('lower',3)
    >>> a_mtrx
    array([[0.38819556, 0.    , 0.        ],
       [0.12304746, 0.07522054, 0.        ],
       [0.96357929, 0.69187941, 0.2878785 ]])

    '''

    assert ndim is None or mtrx is None, 'ndim or mtrx must be given; not both.'
    assert not (ndim is None and mtrx is None), 'either ndim or mtrx must be given.'
    assert mode =='lower' or mode =='upper', 'invalid mode %r.'%mode
    
    if mtrx is None:
        import numpy as np
        mtrx = np.random.random((ndim,ndim))
    else:
        assert mtrx.shape[0] == mtrx.shape[1], 'matrix not square.' 
    
    # ready to return matrix  
    if mode == 'lower':
        for i in range(mtrx.shape[0]):
            mtrx[i,i+1:] = 0.0
    elif mode == 'upper':
        for j in range(mtrx.shape[1]):
            mtrx[j+1:,j] = 0.0
    else:
        assert False, 'oops. something is very wrong.'

    return mtrx      
```

## Conditionals<a id="conditionals"></a>
Constructs that allow branching of operations. The most importants are:
 1. `assert` statement
 1. `if` statement

### `Assert` statement<a id="assert"></a>
The general format is:
```python
    assert test, string(formatted)
```
and it tests for whether `test` is `True`.

### Examples
```python
    assert ndim is None or mtrx is None, 'ndim or mtrx must be given; not both.'
    assert not (ndim is None and mtrx is None), 'either ndim or mtrx must be given.'
    assert mode =='lower' or mode =='upper', 'invalid mode %r.'%mode
```

In [5]:
'''Testing examples'''

import numpy as np

mode = 'lower'
ndim = None
ndim = 1
mtrx = np.random.random((3,4))

#assert ndim is None or mtrx is None, 'eithe ndim or mtrx must be given; not both'

#mtrx = None
assert not (ndim is None and mtrx is None), 'either ndim or mtrx must be given.'

#mode = 'dontknow'
assert mode =='lower' or mode =='upper', 'invalid mode %r.'%mode

### `If` statement<a id='if'></a>
The general format is:
```python
if test1:        # if test
    statements1  # associated block
elif test2:      # optional elifs
    statements2
elif test3:      # more optional elifs etc.
    statements3
else:            # optional final else
    statements4
```

### Example
If-else example:
```python
    if mtrx is None:      # test if mtrx has type None
        import numpy as np
        mtrx = np.random.random((n,n))  # associated block
    else:                 # final test
        assert mtrx.shape[0] == mtrx.shape[1] # l_mtrx must be square
```

In [6]:
'''Testing example'''

test = 3 # change this to 1, 2 or 3

# test setup (uses multiway branching)
if test == 1:
    mtrx = None
    n = 4
elif test == 2:
    import numpy as np
    mtrx = np.array( [ [3.4, 2.1, 4.5],
                       [0.0, 2.0, 1.0] 
                     ] )
elif test == 3:
    import numpy as np
    mtrx = np.array( [ [ 3.4,  2.1,  4.5],
                       [ 0.0,  2.0,  1.0],
                       [-1.0, -3.0, -5.0]
                     ] )
else:
    assert False,'test must be 1, 2, or 3.'

# What we are really testing
#---------------------------------------------------------------    
if mtrx is None:      # test if mtrx has type None
    import numpy as np
    mtrx = np.random.random((n,n))  # associated block
else:                 # final test
    assert mtrx.shape[0] == mtrx.shape[1],'matrix not square.'
#---------------------------------------------------------------
    
print(mtrx)

[[ 3.4  2.1  4.5]
 [ 0.   2.   1. ]
 [-1.  -3.  -5. ]]


### Example
Multiway branching example:
```python
    # ready to return matrix  
    if mode == 'lower':                 # test if mode is 'lower'
        for i in range(mtrx.shape[0]):  # associated block of statements
            mtrx[i,i+1:] = 0.0
    elif mode == 'upper':               # test if mode is 'upper'
        for j in range(mtrx.shape[1]):  # associated block of statements
            mtrx[j+1:,j] = 0.0
    else:                               # final test
        assert False, 'oops. something is very wrong.' # associated block
```

In [7]:
'''Testing example'''

import numpy as np
test = 1  # change this to 1 or 2

mtrx = np.array([[ 3.4,  2.1,  4.5],
                 [ 0.0,  2.0,  1.0],
                 [-1.0, -3.0, -5.0]
                ])
# test setup (uses multiway branching)
if test == 1:
    mode = 'lower'
    
elif test == 2:
    mode = 'upper'
else:
    assert False,'test must be 1 or 2.'
    
# What we are really testing
#---------------------------------------------------------------    
# ready to return matrix  
if mode == 'lower':                 # test if mode is 'lower'
    for i in range(mtrx.shape[0]):  # associated block of statements
            mtrx[i,i+1:] = 0.0
elif mode == 'upper':               # test if mode is 'upper'
    for j in range(mtrx.shape[1]):  # associated block of statements
        mtrx[j+1:,j] = 0.0
else:                               # final test
    assert False, 'oops. something is very wrong.' # associated block
#---------------------------------------------------------------
    
print(mtrx)

[[ 3.4  0.   0. ]
 [ 0.   2.   0. ]
 [-1.  -3.  -5. ]]


## Loops<a id="loops"></a>
Contructs that allow repetitive actions on data. There are two basic types: 
 1. `for` loops
 2. `while` loops

### `For` loops<a id='for'></a>
The general format is:
```python
for target in object: # assign object items to target
    statements        # repeated loop body: (possibly) use target
    if test: 
        break         # exit loop now; skip else
    if test: 
        continue      # go to top of the loop now
else:                 # optional else part
    statements        # if did not hit a `break`
```

### Example
```python
for i in range(mtrx.shape[0]): # assign i to objects in range(mtrx.shape[0])
    mtrx[i,i+1:] = 0.0         # loop over this statement with varying i
```

In [8]:
'''Testing example'''

import numpy as np

mtrx = np.random.random((5,5))
print(mtrx)

m_rows = mtrx.shape[0]

for i in range(m_rows):  # assign i to objects in range(m_rows)
    print('i =',i)
    mtrx[i,i+1:] = 0.0  
    
print(mtrx)

[[0.2444724  0.2083957  0.56302892 0.30498415 0.57955505]
 [0.49381782 0.04769136 0.5445589  0.29788889 0.02961936]
 [0.60831477 0.35580501 0.25503186 0.31375166 0.0086011 ]
 [0.26426191 0.21343588 0.72871477 0.72227452 0.60025511]
 [0.2614883  0.68339246 0.2534688  0.93524169 0.47789712]]
i = 0
i = 1
i = 2
i = 3
i = 4
[[0.2444724  0.         0.         0.         0.        ]
 [0.49381782 0.04769136 0.         0.         0.        ]
 [0.60831477 0.35580501 0.25503186 0.         0.        ]
 [0.26426191 0.21343588 0.72871477 0.72227452 0.        ]
 [0.2614883  0.68339246 0.2534688  0.93524169 0.47789712]]


### `While` loops
We will revisit this when we need this construct.

## Functions<a id="functions"></a>
In simple terms, functions are an efficient alternative to *cutting and pasting* code. They increase code reuse, allow for modularity, and are indispensible to software/code design. An initial format of the functions we will use is:
```python
def name(arg1, arg2,... argN):
    statements
    ...
    statements
    return result # optional but almost always present
```
The function block has its own scope and no variable name is accessible inside the function unless it is passed through the argument list.

### Example<a id="get_triangular_matrix"></a>
```python
def get_triangular_matrix( mode='lower', ndim=None, mtrx=None ):

    assert ndim is None or mtrx is None, 'ndim or mtrx must be given; not both.'
    assert mode =='lower' or mode =='upper', 'invalid mode %r.'%mode
    
    if mtrx is None:
        import numpy as np
        mtrx = np.random.random((ndim,ndim))
    else:
        assert mtrx.shape[0] == mtrx.shape[1], 'matrix not square.' 
    
    # ready to return matrix  
    if mode == 'lower':
        for i in range(mtrx.shape[0]):
            mtrx[i,i+1:] = 0.0
    elif mode == 'upper':
        for j in range(mtrx.shape[1]):
            mtrx[j+1:,j] = 0.0
    else:
        assert False, 'oops. something is very wrong.'
        
    return mtrx     
```

In [9]:
'''Testing the example'''

import numpy as np
np.set_printoptions(precision=3) 

# no arguments will fail
#a_mtrx = get_triangular_matrix()

In [10]:
'''Testing the example'''

# one-argument call
size = 5
out_mtrx = get_triangular_matrix(ndim=size)
print('out_mtrx =\n',out_mtrx)

out_mtrx =
 [[0.982 0.    0.    0.    0.   ]
 [0.242 0.828 0.    0.    0.   ]
 [0.718 0.015 0.806 0.    0.   ]
 [0.409 0.343 0.043 0.356 0.   ]
 [0.802 0.621 0.857 0.708 0.577]]


In [11]:
'''Testing the example'''

# one-argument call
in_mtrx = np.random.random((size,size))
out_mtrx = get_triangular_matrix(mtrx=in_mtrx)
print('out_mtrx =\n',out_mtrx)

out_mtrx =
 [[0.374 0.    0.    0.    0.   ]
 [0.422 0.711 0.    0.    0.   ]
 [0.056 0.894 0.152 0.    0.   ]
 [0.326 0.561 0.721 0.418 0.   ]
 [0.826 0.713 0.083 0.155 0.35 ]]


In [12]:
'''Testing the example'''

# two-argument conflicting call will fail
#out_mtrx = get_triangular_matrix(ndim=size, mtrx=in_mtrx)

'Testing the example'

In [13]:
'''Testing the example'''

# passing argument by object reference
in_mtrx = np.random.random((size,size))
print('in_mtrx before =\n',in_mtrx)

out_mtrx = get_triangular_matrix(mtrx=in_mtrx)

print('in_mtrx after =\n',in_mtrx)
print('out_mtrx =\n',out_mtrx)

in_mtrx before =
 [[0.257 0.389 0.169 0.277 0.016]
 [0.149 0.029 0.79  0.238 0.024]
 [0.694 0.128 0.581 0.821 0.784]
 [0.686 0.623 0.973 0.827 0.41 ]
 [0.945 0.539 0.089 0.43  0.146]]
in_mtrx after =
 [[0.257 0.    0.    0.    0.   ]
 [0.149 0.029 0.    0.    0.   ]
 [0.694 0.128 0.581 0.    0.   ]
 [0.686 0.623 0.973 0.827 0.   ]
 [0.945 0.539 0.089 0.43  0.146]]
out_mtrx =
 [[0.257 0.    0.    0.    0.   ]
 [0.149 0.029 0.    0.    0.   ]
 [0.694 0.128 0.581 0.    0.   ]
 [0.686 0.623 0.973 0.827 0.   ]
 [0.945 0.539 0.089 0.43  0.146]]


### Example: forward substitution solve<a id="forward_solve"></a>
 + Import module as described [before.](#modules)
 + `!cat` the `chen_3170/help.py` file to get the source code for the `forward_solve` function. Then copy into the a markdown cell and add a code fence block to display the source code.

In [14]:
'''Import module'''

from chen_3170.help import forward_solve
help(forward_solve)

Help on function forward_solve in module chen_3170.help:

forward_solve(l_mtrx, b_vec, loop_option='use-dot-product')
    Performs a forward solve with a lower triangular matrix and right side vector.
    
    Parameters
    ----------
    l_mtrx: numpy.ndarray, required
            Lower triangular matrix.
    b_vec:  numpy.ndarray, required
            Right-side vector.
    loop_option: string, optional
            This is an internal option to demonstrate the usage of an explicit
            double loop or an implicit loop using a dot product.
            Default: 'use-dot-product'
    
    Returns
    -------
    x_vec: numpy.narray
           Solution vector returned.
    
    Examples
    --------



In [ ]:
'''View the source code in the notebook'''

!cat "chen_3170/help.py" # ugly but works for now

```python
 def forward_solve(l_mtrx, b_vec, loop_option='use-dot-product'):
    '''
    Performs a forward solve with a lower triangular matrix and right side vector.
    
    Parameters
    ----------
    l_mtrx: numpy.ndarray, required
            Lower triangular matrix.
    b_vec:  numpy.ndarray, required
            Right-side vector.
    loop_option: string, optional
            This is an internal option to demonstrate the usage of an explicit 
            double loop or an implicit loop using a dot product. 
            Default: 'use-dot-product'
            
    Returns
    -------
    x_vec: numpy.narray
           Solution vector returned.
           
    Examples
    --------
    
    '''        
    import numpy as np
    
    # sanity test
    assert isinstance(l_mtrx,np.ndarray)      # l_mtrx must be np.ndarray
    assert l_mtrx.shape[0] == l_mtrx.shape[1],'non-square matrix.' # l_mtrx must be square
    assert np.all(np.abs(np.diagonal(l_mtrx)) > 0.0),'zero value on diagonal.'
    rows_ids, cols_ids = np.where(np.abs(l_mtrx) > 0) # get i, j of non zero entries
    assert np.all(rows_ids >= cols_ids),'non-triangular matrix.' # test i >= j
    assert b_vec.shape[0] == l_mtrx.shape[0],'incompatible l_mtrx @ b_vec dimensions'  # b_vec must be compatible to l_mtrx
    assert loop_option == 'use-dot-product' or loop_option == 'use-double-loop'
    # end of sanity test
    
    m_rows = l_mtrx.shape[0]
    n_cols = m_rows
    x_vec = np.zeros(n_cols)
    
    if loop_option == 'use-dot-product':
        
        for i in range(m_rows):
            sum_lx = np.dot( l_mtrx[i,:i], x_vec[:i] )
            #sum_lx = l_mtrx[i,:i] @ x_vec[:i] # matrix-vec mult. alternative to dot product
            x_vec[i] = b_vec[i] - sum_lx
            x_vec[i] /= l_mtrx[i,i]
            
    elif loop_option == 'use-double-loop':
             
        for i in range(m_rows):
            sum_lx = 0.0
            for j in range(i):
                sum_lx += l_mtrx[i,j] * x_vec[j]
            x_vec[i] = b_vec[i] - sum_lx
            x_vec[i] /= l_mtrx[i,i]
               
    else:
        assert False, 'not allowed option: %r'%loop_option
        
    return x_vec  
```

A lower triangular matrix allows for a forward solve.
The algorithm for $\Lmtrx\,\xvec=\bvec$ is as follows: 

\begin{equation*}
x_i = \Bigl(b_i - \sum\limits_{j=1}^{i-1} L_{i,j}\,x_j \Bigr)\,L^{-1}_{i,i} \quad\ \forall \quad\ i=1,\ldots,m
\end{equation*}

**for $i$ and $j$ with offset 1**. Recall that `NumPy` and `Python` have offset 0 for their sequence data types.

In [16]:
'''Testing the example'''

import numpy as np

size = 5

l_mtrx = get_triangular_matrix( ndim=size )

b_vec  = np.random.random(size)
x_vec  = forward_solve( l_mtrx, b_vec )

np.set_printoptions(precision=3)
print('l_mtrx=\n',l_mtrx)
print('b_vec=',b_vec)
print('x_vec =',x_vec)

l_mtrx=
 [[0.437 0.    0.    0.    0.   ]
 [0.256 0.482 0.    0.    0.   ]
 [0.831 0.857 0.894 0.    0.   ]
 [0.064 0.039 0.058 0.341 0.   ]
 [0.318 0.619 0.805 0.831 0.196]]
b_vec= [0.428 0.044 0.191 0.842 0.063]
x_vec = [ 0.978 -0.428 -0.284  2.387 -8.872]


In [17]:
'''Testing the example'''

# rectangular matrix fails
l_mtrx = np.ones((size,size+1))
b_vec  = np.random.random(size)
#x_vec = forward_solve( l_mtrx, b_vec )

In [18]:
'''Testing the example'''

# zero element on diagonal matrix fails
l_mtrx = get_triangular_matrix(ndim=size)
l_mtrx[size-1,size-1] = 0.0
b_vec  = np.random.random(size)
x_vec = forward_solve( l_mtrx, b_vec )

AssertionError: zero value on diagonal.

## Input/Output<a id="io"></a>
Reading and writing data to persistent storage is needed so that external data is used in a python program or data is saved to disk for future use. This section will list IO operations used in this course. A file is a storage compartment managed by the underlying operating system. Access these files is provided in Python through the built-in function `open` that creates a file object. Using this file object and its methods, data can be transferred in and out of a Python program.
The general format of `open` is:
```python
import io                   # import io module
file = open(filename, mode) # create file object
file.method()               # use a file method
```

### Read "text"<a id="itext"></a>

<div class="alert alert-block alert-info">
This is often referred to as reading formated ASCII data from a file. Simply put, if the file can be displayed with a common text editor, the data is in ASCII format. For example the (partial heptane combustion reaction mechanism) file in the course repository `data/`: [rxn-mech.txt](https://github.com/dpploy/chen-3170/blob/master/data/rxn-mech.txt).
<p>
Reading text in Python will always result into a string type.
</p>
</div>

In [19]:
'''Open file (heptane combustion (incomplete))'''

# open file in reading mode 'r' (default), text 't' (default)
finput = open('data/heptane-rxn.txt','rt')
print(type(finput))

<class '_io.TextIOWrapper'>


In [ ]:
'''Help on open'''

help(open)

In [ ]:
'''Methods of finput = open()'''

dir(finput)

In [ ]:
'''Example of a read method finput.read()'''

help(finput.read)

In [ ]:
'''Let's peek into the file'''

!cat 'data/heptane-rxn.txt'

In [ ]:
'''Minimalist approach'''

# do nothing (i.e. no direct method) just iterate on the file
for line in finput:
    print('line =',line) # the line object has an `end of line` character

In [22]:
'''Artifact in reading text'''

print(type(line))
print('line =',line)
print('chars =',[i for i in line]) # inspect character by character

<class 'str'>
line = C3H4-P+HO2<=>C2H4+CO+OH

chars = ['C', '3', 'H', '4', '-', 'P', '+', 'H', 'O', '2', '<', '=', '>', 'C', '2', 'H', '4', '+', 'C', 'O', '+', 'O', 'H', '\n']


In [23]:
'''Removing artifact'''

reaction = list()

reaction.append( line.strip() ) # leading and trailing spaces; remove end of line special character \n
print('reaction =',reaction) 
print('chars =',[i for i in reaction[0]])

reaction = ['C3H4-P+HO2<=>C2H4+CO+OH']
chars = ['C', '3', 'H', '4', '-', 'P', '+', 'H', 'O', '2', '<', '=', '>', 'C', '2', 'H', '4', '+', 'C', 'O', '+', 'O', 'H']


In [24]:
'''Manipulate reactions'''

print('split = ',reaction[0].split('<') )
left = reaction[0].split('<')[0]
print('left side =',left)

print('split =',reaction[0].split('>'))
right = reaction[0].split('>')[1]
print('right side =',right)

split =  ['C3H4-P+HO2', '=>C2H4+CO+OH']
left side = C3H4-P+HO2
split = ['C3H4-P+HO2<=', 'C2H4+CO+OH']
right side = C2H4+CO+OH


In [25]:
'''Manipulate species'''

species = left.split('+') + right.split('+')
print('species =',species)

species = ['C3H4-P', 'HO2', 'C2H4', 'CO', 'OH']
