ChEn-3170: Computational Methods in Chemical Engineering Fall 2020 UMass Lowell; Prof. V. F. de Almeida **08Sep20**

# Laboratory Work 02 (10Sep20)


### Name: `Julie St.Cyr  `

### Rubric for each assignment: 

|       Context              |  Points |
| -----------------------     | ------- |
| Precision of the answer     |   80%   |
| Answer Markdown readability |   10%   |
| Code readability            |   10%   |
    

### <span style="color:red">Guidance:</span>

+  <span style="color:red"> 
    Save your work frequently to a file locally to your computer.
   </span>
+  <span style="color:red">
    During your work and before submitting the final version do:</span> Kernel -> Restart & Run All<span style="color:red">, to verify your notebook runs correctly.
   </span>
+  <span style="color:red">
    Save your file again.
   </span>
+  <span style="color:red">
    Upload the notebook file: 
   </span> labwork-xx.ipynb<span style="color:red"> on Blackboard.</span>

---
## Table of Assignments<a id="toa"></a>
* [Assignment 1 (20 pts)](#a1)
 - [Chemical species data structure](#a11)
 - [Explain your data structure](#a12)
 - [Output data structure](#a13)
* [Assignment 2 (20 pts)](#a2)
 - [Chemical reactions data structure](#a21)
 - [Explain your data structure](#a22)
 - [Output data structure](#a23)
* [Assignment 3 (20 pts)](#a3)
 - [Chemical reactions data structure](#a31)
 - [Explain your data structure](#a32)
 - [Output data structure](#a33)
* [Assignment 4 (20 pts)](#a4)
 - [Molar mass vector](#a41)
 - [Vector dot product](#a42)
* [Assignment 5 (15 pts)](#a5)
* [Assignment 6 (5 pts)](#a6)
---

## <span style="color:blue">[Assignment 1 (20 pts)](#toa)</span><a id="a1"></a>

### <span style="color:blue">[1.1](#toa) Create variables to store the molecular formula and molar mass of the following species: </span> <a id="a11"></a>
  + <span style="color:blue"> methane, </span>
  + <span style="color:blue"> molecular oxygen, </span>
  + <span style="color:blue"> carbon dioxide, </span>
  + <span style="color:blue"> molecular hydrogen, </span>
  + <span style="color:blue"> water, and </span>
  + <span style="color:blue"> carbon monoxide. </span>

In [10]:
'''Code'''


methane = {'formula':'CH4', 'mass': '16'}
molecular_oxygen = {'formula':'O2', 'mass':'16'}
carbon_dioxide = {'formula':'CO2', 'mass':'44'}
molecular_hydrogen = {'formula':'H2', 'mass':'2'}
water = {'formula':'H2O', 'mass':'18'}
carbon_monoxide = {'formula':'CO', 'mass':'20'}

### <span style="color:blue">[1.2](#toa) Explain (reader-focused) your data structure: </span> <a id="a12"></a>

**Answer:**
+ To create a data structure you need to state what you want and what defines it
+ You must use the swigly brackets for defining instead of normal parenthesis to create a dictionary. 
+ A data structure is a set of code that holds informaiton so that as you code furthur you can refenrce the information about the ertain item. 
+ You use colon to set what you want to define, as seen for the fomula if it wants to be CH4 you would do 'formula':'CH4'

### <span style="color:blue"> [1.3](#toa) Provide an output as follows:</span> <a id="a13"></a>

In [2]:
'''Code'''

CH4 = {'formula':'CH4', 'molar_mass': '16'}
O2 = {'formula':'O2', 'molar_mass':'16'}
CO2 = {'formula':'CO2', 'molar_mass':'44'}
H2 = {'formula':'H2', 'molar_mass':'2'}
H2O = {'formula':'H2O', 'mass':'18'}
CO = {'formula':'CO', 'molar_mass':'20'}


print('CH4 = ',CH4)
print('O2 = ',O2)
print('CO2= ',CO2)
print('H2= ',H2)
print('CO= ',CO)

CH4 =  {'formula': 'CH4', 'molar_mass': '16'}
O2 =  {'formula': 'O2', 'molar_mass': '16'}
CO2=  {'formula': 'CO2', 'molar_mass': '44'}
H2=  {'formula': 'H2', 'molar_mass': '2'}
CO=  {'formula': 'CO', 'molar_mass': '20'}


## <span style="color:blue">[Assignment 2 (20 pts)](#toa)</span> <a id="a2"></a>

### <span style="color:blue">[2.1](#toa) Using the work from Assignment 1, create a data structure to store each of the following chemical reactions for methane oxidation: </span> <a id="a21"></a>

1. $\ \ $  1 methane + 1 molecular oxygen = 1 carbon dioxide + 2 molecular hydrogen
1. $\ \ $  2 molecular hydrogen + 1 molecular oxygen = 2 water
1. $\ \ $  2 carbon monoxide + 4 molecular hydrogen = 2 methane + 1 molecular oxygen

In [29]:
'''code'''

CH4 = {'formula':'CH4', 'molar_mass': '16'}        #Molecule Dictionary 
O2 = {'formula':'O2', 'molar_mass':'16'}
CO2 = {'formula':'CO2', 'molar_mass':'44'}
H2 = {'formula':'H2', 'molar_mass':'2'}
H2O = {'formula':'H2O', 'mass':'18'}
CO = {'formula':'CO', 'molar_mass':'20'}


rxn1 = [H2['formula'],                 #Rxn 1 Dictionary 
        O2['formula'],
        CO2['formula'],
        H2['formula']]

rxn2 = [H2['formula'],                        #Rxn 2 dictionary 
         O2['formula'],
        H2O['formula']]

rxn3 = [CO['formula'],                       #Rxn 3 dictionary 
        H2['formula'],
        CH4['formula'],
        O2['formula']]

print ('1. ', '1', rxn1[0],'+','1',rxn1[1],'=','1',rxn1[2],'+','2',rxn1[3])
print ('2. ', '2', rxn2[0],'+','1',rxn2[1],'=','2',rxn2[2])
print ('3. ', '2', rxn3[0],'+','4',rxn3[1],'=','2',rxn3[2],'+','1',rxn3[3])


1.  1 H2 + 1 O2 = 1 CO2 + 2 H2
2.  2 H2 + 1 O2 = 2 H2O
3.  2 CO + 4 H2 = 2 CH4 + 1 O2


### <span style="color:blue">[2.2](#toa) Explain (reader-focused) your data structure.</span><a id="a22"></a>

**Answer:**
+ First you must make a dictionary. This will store the information about the chemical molecule. This is explained above. 
+ Then you need to create a new dictionary for each reaciton which can pull informaiton form the original dictionary. This can be held as a list. 
+ Each data point you want you need to assign a key starting with 0 to allow you to reference it. 
+ Then you need to print out which parts of the dictionary you want plus the coeffients and the mathetmatical signs. To refernece data in the dictionary use the key you assigned it.  

### <span style="color:blue">[2.3](#toa) Print your data structure to produces the entire reaction set as follows.</span><a id="a23"></a>

In [32]:
'''code'''

CH4 = {'formula':'CH4', 'molar_mass': '16'}        #Molecule Dictionary 
O2 = {'formula':'O2', 'molar_mass':'16'}
CO2 = {'formula':'CO2', 'molar_mass':'44'}
H2 = {'formula':'H2', 'molar_mass':'2'}
H2O = {'formula':'H2O', 'mass':'18'}
CO = {'formula':'CO', 'molar_mass':'20'}


rxn1 = [H2['formula'],                 #Rxn 1 Dictionary 
        O2['formula'],
        CO2['formula'],
        H2['formula']]

rxn2 = [H2['formula'],                        #Rxn 2 dictionary 
         O2['formula'],
        H2O['formula']]

rxn3 = [CO['formula'],                       #Rxn 3 dictionary 
        H2['formula'],
        CH4['formula'],
        O2['formula']]

print ('1. ', '1', rxn1[0],'+','1',rxn1[1],'<=>','1',rxn1[2],'+','2',rxn1[3])
print ('2. ', '2', rxn2[0],'+','1',rxn2[1],'<=>','2',rxn2[2])
print ('3. ', '2', rxn3[0],'+','4',rxn3[1],'<=>','2',rxn3[2],'+','1',rxn3[3])


1.  1 H2 + 1 O2 <=> 1 CO2 + 2 H2
2.  2 H2 + 1 O2 <=> 2 H2O
3.  2 CO + 4 H2 <=> 2 CH4 + 1 O2


## <span style="color:blue">[Assignment 3 (20 pts)](#toa)</span><a id="a3"></a>

### <span style="color:blue">[3.1](#toa) Build a vector of signed stoichiometric coefficients for each reaction.
</span><a id="a31"></a>

In [13]:
'''Code'''
import numpy as np   #import numpy

pylist= [-1,-1,1,2]                  #array for rxn 1 stoichiometric ratios 
stoic_rxn1  = np.array(pylist)

pylist=[-2,-1,2]                    #array for rxn 2 stoichiometric ratios 
stoic_rxn2=np.array(pylist)

pylist= [-2,-4,2,1]                #array for rxn 3 stoichiometric ratios 
stoic_rxn3=np.array(pylist)

print(stoic_rxn1)
print(stoic_rxn2)
print(stoic_rxn3)

[-1 -1  1  2]
[-2 -1  2]
[-2 -4  2  1]


### <span style="color:blue">[3.2](#toa) Explain (reader-focused) your data structure.</span><a id="a32"></a>

**Answer:**
+ To create an array you must first download the extension data numpy. It is common to shorten it to np for easier refernece in the future
+ Then create a pylist of the data you want to store with in it, here the coeiffients 
+ Then assign the pylist niumpy array to a variable, in this I assigned it to the reaction it goes to
+ Then you are able to print it out 

### <span style="color:blue">[3.3](#toa) Provide an output of the data as follows.
</span>
<a id="a33"></a>

In [15]:
'''Code'''

import numpy as np                      #import numpy
pylist= [-1,-1,1,2]                     #array for rxn 1 stoichiometric ratios 
stoic_rxn1  = np.array(pylist)

pylist=[-2,-1,2]                       #array for rxn 2 stoichiometric ratios 
stoic_rxn2=np.array(pylist)

pylist= [-2,-4,2,1]                    #array for rxn 3 stoichiometric ratios 
stoic_rxn3=np.array(pylist)

print('stoic_rxn 1 = ', stoic_rxn1)
print('stoic_rxn 2 = ',stoic_rxn2)
print('stoic_rxn 3 = ',stoic_rxn3)

stoic_rxn 1 =  [-1 -1  1  2]
stoic_rxn 2 =  [-2 -1  2]
stoic_rxn 3 =  [-2 -4  2  1]


## <span style="color:blue">[Assignment 4 (20 pts)](#toa)</span><a id="a4"></a>

### <span style="color:blue">[4.1](#toa) For each reaction, build a vector of molar mass values for the species involved and print the vector data.</span><a id="a41"></a>

In [19]:
'''Code'''
import numpy as np   #import numpy

pylist= [16,32,44,2]                     #Array for molar masses in rxn 1
molar_massrxn1 = np.array(pylist)

pylist = [2,32,18]                      #Array for molar masses in rxn 2
molar_massrxn2 = np.array(pylist)

pylist = [28, 2, 16, 32]                #Array for molar masses in rxn 3
molar_massrxn3= np.array(pylist)

print ('molar masses per reaction')
print (molar_massrxn1)
print(molar_massrxn2)
print(molar_massrxn3)

molar masses per reaction
[16 32 44  2]
[ 2 32 18]
[28  2 16 32]


### <span style="color:blue">[4.2](#toa) For each reaction, multiply the vector of species mass values, created in 4.1, by the corresponding vector of signed stoichiometric coefficients in Assignment 3. Print the resulting vectors.</span><a id="a42"></a>

In [22]:
'''Code'''
import numpy as np   #import numpy

pylist= [-1,-1,1,2]                #stoi rxn1
stoic_rxn1  = np.array(pylist)

pylist=[-2,-1,2]                 #stoic rxn 2
stoic_rxn2=np.array(pylist)

pylist= [-2,-4,2,1]
stoic_rxn3=np.array(pylist)              #stoic rxn 3

pylist= [16,32,44,2]                    #molar mass rxn1
molar_massrxn1 = np.array(pylist)

pylist = [2,32,18]                     #molar mass rxn 2 
molar_massrxn2 = np.array(pylist)

pylist = [28, 2, 16, 32]              #molar mass rxn 3 
molar_massrxn3= np.array(pylist)

print('stoichiometric coeffiecient vector product with molar masses')      #Print of multiplication of stoi and mass 
print (molar_massrxn1*stoic_rxn1)
print (molar_massrxn2*stoic_rxn2)
print (molar_massrxn3*stoic_rxn3)

stoichiometric coeffiecient vector product with molar masses
[-16 -32  44   4]
[ -4 -32  36]
[-56  -8  32  32]


## <span style="color:blue">[Assignment 5 (15 pts)](#toa)</span><a id="a5"></a>

### <span style="color:blue">For each vector in Assignment 4.2, sum all the entries per vector, provide the output of the results, and explain the numerical results obtained.</span>

In [28]:
'''Code'''
import math 
import numpy as np   #import numpy


pylist= [-1,-1,1,2]                #stoi rxn1
stoic_rxn1  = np.array(pylist)

pylist=[-2,-1,2]                 #stoic rxn 2
stoic_rxn2=np.array(pylist)

pylist= [-2,-4,2,1]
stoic_rxn3=np.array(pylist)              #stoic rxn 3

pylist= [16,32,44,2]                    #molar mass rxn1
molar_massrxn1 = np.array(pylist)

pylist = [2,32,18]                     #molar mass rxn 2 
molar_massrxn2 = np.array(pylist)

pylist = [28, 2, 16, 32]              #molar mass rxn 3 
molar_massrxn3= np.array(pylist)


rxn1 = molar_massrxn1*stoic_rxn1                      #multipliaction of molar mass and stoic ratio
rxn2 = molar_massrxn2*stoic_rxn2
rxn3 = molar_massrxn3*stoic_rxn3

rxn1_sum = rxn1.sum()                              #sum of the arrays created in combination of mass and stoic
rxn2_sum = rxn2.sum()
rxn3_sum = rxn3.sum()

print(rxn1_sum)
print(rxn2_sum)
print(rxn3_sum)

0
0
0


**Explanation of results:**
+ The reason all three answers come out to 0 is because for a balences equation the number of each atom is equal meaning if there are 4 oxygens in the reactants there should be 4 oxygens in the products. Since each atom can be reporesented by their molar mass, the molar mass multiplied by the stoiciometic ratio which evens the equation out would make it so the same number would be on each side just one being the negative. Since the arrays held the reactants as negatives and the products as positive the sums will eliminate to 0. 

## <span style="color:blue">[Assignment 6 (5 pts)](#toa)</span><a id="a6"></a>

### <span style="color:blue">Describe the most unclear point in the content presented so far. Then, make an effort to clarify the point on your own.</span>

+ I managed to figure out how to refer a dictionary in a new dictionary however that was a big quesiton for most of this lab. Assignment 2 was the hardest the rest I feel I understood very well. 
+ Is there a different way to approach this will out creating two different dicitonaries? 