ChEn-3170: Computational Methods in Chemical Engineering Fall 2018 UMass Lowell; Prof. V. F. de Almeida **13Sep2018**

# Laboratory Work 02 13Sep2018 Session 802

### Name: `your name`

### Rubric for each assignment: 

|                             |  Points |
| -----------------------     | ------- |
| Precision of the answer     |   80%   |
| Answer Markdown readability |   10%   |
| Code readability            |   10%   |
    

### <span style="color:red">Guidance:</span>
 +  <span style="color:red"> 
    Save your work frequently to a file locally to your computer.
    </span>
 +  <span style="color:red">
    During your work and before submitting the final version do: `Kernel` -> `Restart & Run All`, to verify your notebook runs correctly.
    </span>
 +  <span style="color:red">
    Save your file again.
    </span>

## <span style="color:blue">Assignment 1 (20 pts).</span>
### <span style="color:blue">Create variables to store the molecular formula and molar mass of the following species: methane, molecular oxygen, carbon dioxide, molecular hydrogen, water, and carbon monoxide. Provide an output.</span>

The variables will be created as Python `dict` data structure with two pairs of `key:value` elements.

In [3]:
#ch4 = dict()
ch4 = {'formula':'CH4', 'molar_mass':16}

#o2 = dict()
o2 = {'formula':'O2', 'molar_mass':32}

#co2 = dict()
co2 = {'formula':'CO2', 'molar_mass':44}

#h2 = dict()
h2 = {'formula':'H2', 'molar_mass':2}

#h2o = dict()
h2o = {'formula':'H2O', 'molar_mass':18}

#co = dict()
co = {'formula':'CO', 'molar_mass':28}

print('ch4 =',ch4)
print('o2 =',o2)
print('co2 =',co2)
print('h2 =',h2)
print('h2o =',h2o)
print('co =', co)

ch4 = {'formula': 'CH4', 'molar_mass': 16}
o2 = {'formula': 'O2', 'molar_mass': 32}
co2 = {'formula': 'CO2', 'molar_mass': 44}
h2 = {'formula': 'H2', 'molar_mass': 2}
h2o = {'formula': 'H2O', 'molar_mass': 18}
co = {'formula': 'CO', 'molar_mass': 28}


## <span style="color:blue">Assignment 2 (20 pts).</span>
### <span style="color:blue">Using the work from Assignment 1, create a way to store each of the chemical reactions for methane oxydation as follows: </span>

1.   2 molecular oxygen + 4 molecular hydrogen = 4 water
1.   4 molecular hydrogen + 2 carbon monoxide  = 2 methane + 1 molecular oxygen
1.   3 molecular oxygen + 3 methane = 6 molecular hydrogen + 3 carbon dioxide

### <span style="color:blue"> so that printing your data structure produces the entire reaction set.</span> 

All reactions will be stored in a `list` structure. One reaction per element in the list.

In [4]:
rxn = list( range(3) )   # place holder for the list with 3 elements

rxn[0] = '2*'+o2['formula']+' + '+'4*'+ h2['formula']+' <=> '+'4*'+h2o['formula']
rxn[1] = '4*'+h2['formula']+' + '+'2*'+ co['formula']+' <=> '+'2*'+ch4['formula']+' + '+'1*'+ o2['formula']
rxn[2] = '3*'+o2['formula']+' + '+'3*'+ch4['formula']+' <=> '+'6*'+ h2['formula']+' + '+'3*'+co2['formula']

print(rxn[0])
print(rxn[1])
print(rxn[2])

2*O2 + 4*H2 <=> 4*H2O
4*H2 + 2*CO <=> 2*CH4 + 1*O2
3*O2 + 3*CH4 <=> 6*H2 + 3*CO2


## <span style="color:blue">Assignment 3 (20 pts).</span>
### <span style="color:blue">Build a vector of signed stoichiometric coefficients for each reaction. Provide an output of the data.
</span>

In view of the next assignments, create a `numpy` vector for each set of stoichiometric coefficient.

In [5]:
import numpy as np

stoic_rxn = [-2, -4, 4]
stoic_rxn1 = np.array(stoic_rxn)

stoic_rxn = [-4,-2, 2, 1]
stoic_rxn2 = np.array(stoic_rxn)

stoic_rxn = [-3, -3, 6, 3]
stoic_rxn3 = np.array(stoic_rxn)

print('stoic_rxn 1 =', stoic_rxn1)
print('stoic_rxn 2 =', stoic_rxn2)
print('stoic_rxn 3 =', stoic_rxn3)

stoic_rxn 1 = [-2 -4  4]
stoic_rxn 2 = [-4 -2  2  1]
stoic_rxn 3 = [-3 -3  6  3]


## <span style="color:blue">Assignment 4 (20 pts).</span>
### <span style="color:blue">For each reaction, build a vector of molar mass values for the species involved and multiply by the corresponding vector of signed stoichiometric coefficients in Assignment 3.</span>


Using element dictionaries previously created, create molar mass vectors for the species involved in the reactions and carry out an element-by-element vector product with the vector of stoichiometric coefficients.

In [6]:
#2*O2 + 4*H2 <=> 4*H2O
#4*H2 + 2*CO <=> 2*CH4 + 1*O2
#3*O2 + 3*CH4 <=> 6*H2 + 3*CO2

molar_mass = [ o2['molar_mass'], h2['molar_mass'], h2o['molar_mass'] ]
molar_mass_rxn1 = np.array(molar_mass)

molar_mass = [ h2['molar_mass'], co['molar_mass'], ch4['molar_mass'], o2['molar_mass'] ]
molar_mass_rxn2 = np.array(molar_mass)

molar_mass = [ o2['molar_mass'], ch4['molar_mass'], h2['molar_mass'], co2['molar_mass'] ]
molar_mass_rxn3 = np.array(molar_mass)

print('molar masses per reaction')
print(molar_mass_rxn1)
print(molar_mass_rxn2)
print(molar_mass_rxn3)

print('')

print('stoichiometric coefficient vector product with molar masses')
stoic_x_molar_mass_rxn1 = stoic_rxn1 * molar_mass_rxn1
print(stoic_x_molar_mass_rxn1)
stoic_x_molar_mass_rxn2 = stoic_rxn2 * molar_mass_rxn2
print(stoic_x_molar_mass_rxn2)
stoic_x_molar_mass_rxn3 = stoic_rxn3 * molar_mass_rxn3
print(stoic_x_molar_mass_rxn3)

molar masses per reaction
[32  2 18]
[ 2 28 16 32]
[32 16  2 44]

stoichiometric coefficient vector product with molar masses
[-64  -8  72]
[ -8 -56  32  32]
[-96 -48  12 132]


## <span style="color:blue">Assignment 5 (20 pts).</span>
### <span style="color:blue">For each vector in Assignment 4, sum all the entries, provide the output of the results, and explain the results obtained.</span>

Perform the mass balance per reaction by summing the product vectors.

In [7]:
print('mass balance per reaction')
print('stoic_x_molar_rxn1 =',np.sum(stoic_x_molar_mass_rxn1))
print('stoic_x_molar_rxn2 =',np.sum(stoic_x_molar_mass_rxn2))
print('stoic_x_molar_rxn3 =',np.sum(stoic_x_molar_mass_rxn3))

mass balance per reaction
stoic_x_molar_rxn1 = 0
stoic_x_molar_rxn2 = 0
stoic_x_molar_rxn3 = 0


This is the statement of mass conservation per chemical reaction.